### ISSUE TITLE
CUSA37934 - NHL 24

### ISSUE THREAD

**Issue by yjgtoastedq** [shadps4-emu/shadps4-game-compatibility#1006]
### Game Name

NHL 24

### Game code

CUSA37934

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.40

### Current status

Nothing

### Operating System

Windows

### Error

<Error> module.cpp:LoadModuleToMemory:196: Unimplemented type SCE Comment
<Error> module.cpp:LoadModuleToMemory:196: Unimplemented type SCE Library Version

### Description

Black screen, nothing appears

### Screenshots

![image](https://github.com/user-attachments/assets/4301e542-5f85-42d6-9b13-ce2154014f3a)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17626269/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicate #364
