### ISSUE TITLE
Dragon Quest Heroes II

### ISSUE THREAD

**Issue by username227** [shadps4-emu/shadps4-game-compatibility#1018]
### Game Name

Dragon Quest Heroes II

### Game code

CUSA06769

### Game version

1.06

### Used emulator's version (only released versions are acceptable)

0.4.1

### Current status

Nothing

### Operating System

Linux

### Error

Segmentation Fault - core dumped

### Description

Get a black pop-up window that lasts a number of seconds and then program crashes.

### Log File

[log.txt](https://github.com/user-attachments/files/17704419/log.txt)

**Comment by C4ndyF1sh** [comment]
0.4.1 isn't applicable, it's a WIP
