### ISSUE TITLE
Dragon Quest Heroes: The World Tree's Woe and the Blight Below

### ISSUE THREAD

**Issue by username227** [shadps4-emu/shadps4-game-compatibility#1019]
### Game Name

Dragon Quest Heroes: The World Tree's Woe and the Blight Below

### Game code

CUSA02694

### Game version

1.0.0

### Used emulator's version (only released versions are acceptable)

0.4.1

### Current status

Nothing

### Operating System

Linux

### Error

Segmentation Fault - Core Dumped

### Description

Black screen pop up followed by pause for a few seconds and then program crashes.

### Log File

[log.txt](https://github.com/user-attachments/files/17704467/log.txt)

**Comment by C4ndyF1sh** [comment]
Only released versions are applicable, not 0.4.1, that is a WIP
