### ISSUE TITLE
CUSA00309 - inFAMOUS Second Son

### ISSUE THREAD

**Issue by Howlvast-Liu** [shadps4-emu/shadps4-game-compatibility#1020]
### Game Name

inFAMOUS Second Son

### Game code

CUSA00309

### Game version

v01.00&v01.07

### Used emulator's version (only released versions are acceptable)

v0.4.1

### Current status

Nothing

### Operating System

Windows

### Error

Not responding

### Description

After playing the opening logo, the game screen goes black and becomes unresponsive

### Screenshots

/

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17704526/shad_log.txt)

**Comment by C4ndyF1sh** [comment]
The tag "status-boots" would fit much better, status-nothing would mean that absolutely nothing happens, not even a intro

**Comment by C4ndyF1sh** [comment]
And only released versions are applicable, so only 0.4.0, 0.4.1 is a WIP
