### ISSUE TITLE
CUSA03173 Issue

### ISSUE THREAD

**Issue by SergiusLOL** [shadps4-emu/shadps4-game-compatibility#1054]
### Game Name

Bloodborne

### Game code

CUSA03173 

### Game version

1.09

### Used emulator's version (only released versions are acceptable)

0.2.1

### Current status

Nothing

### Operating System

Windows

### Error

Cant open game

### Description

When i open the game already charge in shadps4 it turns in black screen and try boot but close at sec and on console appear this screenshoot

### Screenshots

![image](https://github.com/user-attachments/assets/71237a0a-b789-4f66-9263-225475de701d)
![image](https://github.com/user-attachments/assets/77168f3b-0568-44e9-9550-b7cf45014357)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17792686/shad_log.txt)

**Comment by C4ndyF1sh** [comment]
Why are you still using 0.2.1? 😭
We at 0.4.1 now

**Comment by SergiusLOL** [comment]
ohhh! i try it at moment work tysm

**Comment by C4ndyF1sh** [comment]
@SergiusLOL Would you mind deleting this ?
