### ISSUE TITLE
CUSA08829 - Call of Duty: Modern Warfare

### ISSUE THREAD

**Issue by Crispy81** [shadps4-emu/shadps4-game-compatibility#1096]
### Game Name

Call of Duty: Modern Warfare

### Game code

CUSA08829

### Game version

1.00

### Used emulator's version (only released versions are acceptable)

0.4

### Current status

Nothing

### Operating System

Windows

### Error

.

### Description

Emulator crashes and closes.

### Screenshots

![Screenshot 2024-11-20 152826](https://github.com/user-attachments/assets/64a8a33d-65da-482a-b8f9-8e9206c2998c)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17824800/shad_log.txt)

**Comment by Hermiten** [comment]
Please update the original one

**Comment by Hermiten** [comment]
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/282
