### ISSUE TITLE
CUSA07098 - Guacamelee! 2

### ISSUE THREAD

**Issue by Crispy81** [shadps4-emu/shadps4-game-compatibility#1175]
### Game Name

Guacamelee! 2

### Game code

CUSA07098

### Game version

1.00

### Used emulator's version (only released versions are acceptable)

0.4

### Current status

Nothing

### Operating System

Windows

### Error

.

### Description

Black screen, does nothing.

### Screenshots

![image](https://github.com/user-attachments/assets/ba544321-f17a-463a-9c69-ec7515c62636)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17860390/shad_log.txt)

**Comment by az511** [comment]
duplicate from #734 if you want to post the update you have to reply to #734
