### ISSUE TITLE
CUSA13721 - ACA NEOGEO METAL SLUG 5

### ISSUE THREAD

**Issue by PistolaoBR** [shadps4-emu/shadps4-game-compatibility#1200]
### Game Name

ACA NEOGEO METAL SLUG 5

### Game code

CUSA13721

### Game version

V01.00

### Used emulator's version (only released versions are acceptable)

v0.4.1 WIP df8284c

### Current status

Ingame

### Operating System

Windows

### Error

No sound, but playeable

### Description

The game runs fine, but without any sound

### Screenshots

![image](https://github.com/user-attachments/assets/dfbc3eb2-bab6-4331-95ca-c075d9c54aa7)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17877575/shad_log.txt)

**Comment by Hermiten** [comment]
Please do your test only on release version, like 0.4
Thanks you
