### ISSUE TITLE
CUSA11740 - METAL SLUG XX

### ISSUE THREAD

**Issue by PistolaoBR** [shadps4-emu/shadps4-game-compatibility#1201]
### Game Name

METAL SLUG XX

### Game code

CUSA11740

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.4.1 WIP df8284c

### Current status

Boots

### Operating System

Windows

### Error

Black Screen

### Description

Black screen

### Screenshots

![image](https://github.com/user-attachments/assets/15994523-9880-4efd-be54-9bab60267381)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17877597/shad_log.txt)

**Comment by Hermiten** [comment]
Please do your test on release version, like 0.4
