### ISSUE TITLE
SLPS25674 - Metal Slug 6

### ISSUE THREAD

**Issue by PistolaoBR** [shadps4-emu/shadps4-game-compatibility#1202]
### Game Name

Metal Slug 6

### Game code

SLPS25674

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.4.1 WIP df8284c

### Current status

Nothing

### Operating System

Windows

### Error

Force closes the emulator

### Description

Force closes the emulator

### Screenshots

![image](https://github.com/user-attachments/assets/cb773021-74df-4a16-be57-2a8ef448203b)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17877610/shad_log.txt)

**Comment by Hermiten** [comment]
Same here
