### ISSUE TITLE
SLUS01212 - Metal Slug X Red Blood

### ISSUE THREAD

**Issue by PistolaoBR** [shadps4-emu/shadps4-game-compatibility#1203]
### Game Name

Metal Slug X Red Blood

### Game code

SLUS01212

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.4.1 WIP df8284c

### Current status

Menus

### Operating System

Windows

### Error

It needs ps4 touchpad to start

### Description

It needs ps4 touchpad to start

### Screenshots

![image](https://github.com/user-attachments/assets/03ffd77e-7b6f-41b0-8668-94e4b4527611)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17877628/shad_log.txt)

**Comment by Hermiten** [comment]
Same here
