### ISSUE TITLE
CUSA50463 - RetroRealms

### ISSUE THREAD

**Issue by PistolaoBR** [shadps4-emu/shadps4-game-compatibility#1204]
### Game Name

RetroRealms

### Game code

CUSA50463

### Game version

v01.03 v01.00

### Used emulator's version (only released versions are acceptable)

v0.4.1 WIP df8284c

### Current status

Nothing

### Operating System

Windows

### Error

Force closes

### Description

Force closes
Tested on:
v01.00
v01.03
v01.03 + 4 DLCs

### Screenshots

![image](https://github.com/user-attachments/assets/651fc691-03e7-401b-9d00-5a869944ecec)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17877702/shad_log.txt)

**Comment by Hermiten** [comment]
Same here
