### ISSUE TITLE
CUSA13413 - Darkwood

### ISSUE THREAD

**Issue by PistolaoBR** [shadps4-emu/shadps4-game-compatibility#1206]
### Game Name

Darkwood

### Game code

CUSA13413

### Game version

v01.00 v01.06

### Used emulator's version (only released versions are acceptable)

v0.4.1 WIP df8284c

### Current status

Nothing

### Operating System

Windows

### Error

Force closes

### Description

Force closes

### Screenshots

![image](https://github.com/user-attachments/assets/bdd08717-c12f-406d-b59f-afd87ce6eab7)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17877776/shad_log.txt)

**Comment by Hermiten** [comment]
Same here
