### ISSUE TITLE
CUSA51046 - Neva

### ISSUE THREAD

**Issue by PistolaoBR** [shadps4-emu/shadps4-game-compatibility#1210]
### Game Name

Neva

### Game code

CUSA51046

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.4.1 WIP df8284c

### Current status

Nothing

### Operating System

Windows

### Error

Force closes

### Description

Force closes

### Screenshots

![image](https://github.com/user-attachments/assets/7eb8da0a-fa2b-4ea1-b2c2-3135d7cb070e)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17877853/shad_log.txt)

**Comment by Crispy81** [comment]
Just as an fyi dude. From the Compatibility documentation:

![image](https://github.com/user-attachments/assets/ce401446-6ebd-4074-bb05-3eb45c8d2c08)

**Comment by Hermiten** [comment]
Same here
