### ISSUE TITLE
CUSA39157 - A Space for the Unbound

### ISSUE THREAD

**Issue by PistolaoBR** [shadps4-emu/shadps4-game-compatibility#1212]
### Game Name

A Space for the Unbound

### Game code

CUSA39157

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.4.1 WIP df8284c

### Current status

Nothing

### Operating System

Windows

### Error

Force closes

### Description

Force closes

### Screenshots

![image](https://github.com/user-attachments/assets/2badd0a0-644b-47b5-9004-9bc6984d68d8)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17877890/shad_log.txt)

**Comment by Hermiten** [comment]
Same here
