### ISSUE TITLE
CUSA24620 - Love Live! School Idol Festival after school ACTIVITY Wai-Wai!Home Meeting!!

### ISSUE THREAD

**Issue by RainKikyou** [shadps4-emu/shadps4-game-compatibility#125]
### Game Name

Love Live! School Idol Festival ~after school ACTIVITY~ Wai-Wai!Home Meeting!! 

### Game code

CUSA24620

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.1.1 WIP

### Current status

Nothing

### Error

Check the emulator log.

### Description

Check the emulator log.

### Screenshots

![QQ图片20240706201238](https://github.com/shadps4-emu/shadps4-game-compatibility/assets/20301499/39c7a129-830f-45ec-ab91-a894342ea764)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16116175/shad_log.txt)

**Comment by georgemoralis** [comment]
currently release version is 0.1.0 , WIP versions is not permitted read rules
