### ISSUE TITLE
CUSA02908 - Hatsune Miku Project Diva X

### ISSUE THREAD

**Issue by RainKikyou** [shadps4-emu/shadps4-game-compatibility#126]
### Game Name

Hatsune Miku Project DIVA X

### Game code

CUSA02908

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.1.1 WIP

### Current status

Nothing

### Error

Check the emulator log.

### Description

Check the emulator log.

### Screenshots

![QQ图片20240706205727](https://github.com/shadps4-emu/shadps4-game-compatibility/assets/20301499/9d4aa1f3-d5cb-45a8-8556-582d3f63edb5)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16116189/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions reports (0.1.0) . Currently 0.1.1 which is WIP
