### ISSUE TITLE
CUSA03567 - Star Ocean 5:Integrity and Faithlessness

### ISSUE THREAD

**Issue by RainKikyou** [shadps4-emu/shadps4-game-compatibility#127]
### Game Name

Star Ocean 5:Integrity and Faithlessness

### Game code

CUSA03567

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.1.1 WIP

### Current status

Nothing

### Error

Check the emulator log.

### Description

Check the emulator log.

### Screenshots

![QQ图片20240706220329](https://github.com/shadps4-emu/shadps4-game-compatibility/assets/20301499/dedec950-23e4-46ef-aa75-84c9f3b5c6f9)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16116358/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions reports (0.1.0) . Currently 0.1.1 which is WIP
