### ISSUE TITLE
F1 23

### ISSUE THREAD

**Issue by asilosfervip** [shadps4-emu/shadps4-game-compatibility#128]
### Game Name

F1®23

### Game code

CUSA36255

### Game version

1.00

### Used emulator's version (only released versions are acceptable)

v0.1.1

### Current status

Nothing

### Error

[Debug] <Critical> thread_management.cpp:scePthreadMutexattrSettype:503: Unreachable code!
Invalid type: 0

### Description

F1 23 no loads

### Screenshots

![image](https://github.com/shadps4-emu/shadps4-game-compatibility/assets/104506980/7f53f557-e7f5-48b4-86fb-3907b7d0c0d5)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16117034/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions reports (0.1.0) . Currently 0.1.1 which is WIP
