### ISSUE TITLE
Rayman Legends crashes after the splash screen

### ISSUE THREAD

**Issue by Adamillo** [shadps4-emu/shadps4-game-compatibility#130]
### Game Name

Rayman Legends

### Game code

CUSA00031

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.1.1 WIP

### Current status

Nothing

### Error

The emulator just closes

### Description

There is nothing useful in the logs either

**Comment by Adamillo** [comment]
It crashes on shadps4 version 0.1.0 as well

**Comment by Brutal-sam** [comment]
idk if this will work, but I had some games crashing after splash, but enabling vulkan validation from the config file and turning off splash screen made them boot into menu

**Comment by Adamillo** [comment]
It goes to menu now thanks to emufan! Idk if it goes ingame or not, but I won't be able to test it for a while

**Comment by georgemoralis** [comment]
very nice but as it already stated on readme that compatibility list is for release versions only (at the time 0.1.0) i have to close it now...
