### ISSUE TITLE
Dying light 2 problem

### ISSUE THREAD

**Issue by Huskyreq** [shadps4-emu/shadps4-game-compatibility#1310]
### Game Name

Dying Light 2:Stay Human

### Game code

CUSA12555

### Game version

1.56

### Used emulator's version (only released versions are acceptable)

V0.4.1

### Current status

Boots

### Operating System

Windows

### Error

[Debug] <Critical> assert.cpp:assert_fail_debug_msg:30: Assertion Failed!
g.IO.Fonts->IsBuilt() && "Font Atlas not built! Make sure you called ImGui_ImplXXXX_NewFrame() function for renderer backend, which should call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()" at D:\a\shadPS4\shadPS4\externals\dear_imgui\imgui.cpp:10723
[Debug] <Critical> assert.cpp:assert_fail_debug_msg:30: Assertion Failed!
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceSslInit (nid: hdpVEUDFW3s) called, returning zero to 0x940928655

### Description

The emulator starts the game but it showing me only a blank screen

### Screenshots

![image_2024-11-26_133806858](https://github.com/user-attachments/assets/625abb55-d578-45cf-855a-cabbf16533d0)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17918760/shad_log.txt)

**Comment by georgemoralis** [comment]
not correct title format
