### ISSUE TITLE
CUSA15634 Windjammers 2

### ISSUE THREAD

**Issue by SonicAdventureX** [shadps4-emu/shadps4-game-compatibility#132]
### Game Name

Windjammers 2

### Game code

CUSA15634

### Game version

1.00

### Used emulator's version (only released versions are acceptable)

v0.1.1

### Current status

Nothing

### Error

Check log

### Description

It tries to boot up. But it kicks me right back out.

### Screenshots

![image](https://github.com/shadps4-emu/shadps4-game-compatibility/assets/39503785/c4be720b-9b55-4728-8c34-f465dfbb17d6)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16118007/shad_log.txt)

**Comment by georgemoralis** [comment]
very nice but as it already stated on readme that compatibility list is for release versions only (at the time 0.1.0) i have to close it now...

**Comment by SonicAdventureX** [comment]
Oh okay Gotcha. Understood.
