### ISSUE TITLE
CUSA32802 - Miss Kobayashis Dragon Maid Burst Forth Chorogon Breath

### ISSUE THREAD

**Issue by nProtect** [shadps4-emu/shadps4-game-compatibility#1322]
### Game Name

Miss Kobayashis Dragon Maid Burst Forth Chorogon Breath

### Game code

CUSA32802

### Game version

v01.01

### Used emulator's version (only released versions are acceptable)

v0.4.1

### Current status

Nothing

### Operating System

Windows

### Error

[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:56: (DUMMY) called module = ORBIS_SYSMODULE_APP_CONTENT
[Lib.AppContent] <Error> app_content.cpp:sceAppContentInitialize:241: (DUMMY) called
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:56: (DUMMY) called module = ORBIS_SYSMODULE_APP_CONTENT
[Lib.AppContent] <Error> app_content.cpp:sceAppContentInitialize:241: (DUMMY) called
[Lib.AppContent] <Info> app_content.cpp:sceAppContentTemporaryDataMount2:316: sceAppContentTemporaryDataMount2: option = 0, mountPoint = /temp0
[Kernel.Fs] <Info> file_system.cpp:posix_open:107: posix open redirect to sceKernelOpen
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/Media/Metadata/global-metadata.dat flags = 0x0 mode = 438
[Kernel.Fs] <Info> file_system.cpp:sceKernelFStat:455: (PARTIAL) fd = 4
[Kernel.Fs] <Info> file_system.cpp:sceKernelFStat:455: (PARTIAL) fd = 4
[Kernel.Fs] <Info> file_system.cpp:sceKernelFStat:455: (PARTIAL) fd = 4
[Kernel.Vmm] <Info> memory.cpp:posix_mmap:473: posix mmap redirect to sceKernelMmap
[Kernel.Vmm] <Info> memory.cpp:sceKernelMmap:456: called addr = 0x0, len = 4009984, prot = 1, flags = 1, fd = 4, offset = 0
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:142: Closing /app0/Media/Metadata/global-metadata.dat
[Kernel.Event] <Info> event_flag.cpp:sceKernelCreateEventFlag:160: called name = resumeEvent attr = 0x21 initPattern = 0x0
[Debug] <Critical> exception.cpp:sceKernelInstallExceptionHandler:77: Unreachable code!
Missing exception implementation

### Description

Game doesn't boot at all and crash emulator.

### Screenshots

![01-emu_crash](https://github.com/user-attachments/assets/c559d733-dc05-4892-b450-8bf325f942c1)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17967956/shad_log.txt)

**Comment by Hermiten** [comment]
Only major release is accepeted for test like 0.4
