### ISSUE TITLE
CUSA34606 - Atelier Ryza 3 Alchemist of The End and The Secret Key

### ISSUE THREAD

**Issue by nProtect** [shadps4-emu/shadps4-game-compatibility#1323]
### Game Name

Atelier Ryza 3 Alchemist of The End and The Secret Key

### Game code

CUSA34606

### Game version

v01.07

### Used emulator's version (only released versions are acceptable)

v0.4.1

### Current status

Menus

### Operating System

Windows

### Error

[Render.Recompiler] <Error> translate.cpp:LogMissingOpcode:452: Unknown opcode V_FREXP_EXP_I32_F32 (526, category = VectorALU)
[Render.Recompiler] <Error> translate.cpp:LogMissingOpcode:452: Unknown opcode V_FREXP_MANT_F32 (527, category = VectorALU)
[Debug] <Critical> scalar_memory.cpp:operator():49: Unreachable code!

### Description

- Graphical glitch.
- Emulator crash while intro cutscene.

### Screenshots

![Screenshot 2024-12-01 125158](https://github.com/user-attachments/assets/b8f3fc26-9f89-4c5d-a2fe-4bedc1699d4e)
![Screenshot 2024-12-01 125253](https://github.com/user-attachments/assets/6e2d16f1-e43f-4e78-9f82-dae16c771fbb)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17967963/shad_log.txt)

**Comment by Hermiten** [comment]
Only major release is accepted like 0.4 to do the test
