### ISSUE TITLE
KINGDOM HEARTS Ⅲ | Serial:CUSA12031 | Version:01.10 | 

### ISSUE THREAD

**Issue by SiriusVI87** [shadps4-emu/shadps4-game-compatibility#1329]
### Game Name

KINGDOM HEARTS Ⅲ

### Game code

CUSA12031 

### Game version

v01.10 

### Used emulator's version (only released versions are acceptable)

v0.4.1

### Current status

Nothing

### Operating System

Windows

### Error

"Failied to open descriptor file" [....] "TresGame.uproject"

### Description

When trying to launch the game, this error appears: "Failied to open descriptor file" [....] "TresGame.uproject"

### Screenshots

![image](https://github.com/user-attachments/assets/daaba6c1-da99-492c-9d0a-1682a9a104b1)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18007854/shad_log.txt)

**Comment by Hermiten** [comment]
We only accept major release version here. Like 0.4
Thanks you
