### ISSUE TITLE
CUSA27766: Flynn: Son of Crimson

### ISSUE THREAD

**Issue by Brutal-sam** [shadps4-emu/shadps4-game-compatibility#133]
### Game Name

Flynn: Son of Crimson

### Game code

CUSA27766

### Game version

1.00

### Used emulator's version (only released versions are acceptable)

0.1.1

### Current status

Playable

### Error

none (only 1 crash first time booting the game, could be the cause of spamming x to skip intro)

### Description

first time running the game and spamming X to skip the intro will crash the game, second boot loading the game save, letting the intro play then proceeding to gameplay smooth without issues, graphics are good, colors good, fps around 60. 

### Screenshots

![1](https://github.com/shadps4-emu/shadps4-game-compatibility/assets/94696121/b17b7136-3fa7-4981-a783-35b50b2b1652)
![2](https://github.com/shadps4-emu/shadps4-game-compatibility/assets/94696121/9a59a947-60d8-4230-aefd-a22e8e1e3c0e)
![3](https://github.com/shadps4-emu/shadps4-game-compatibility/assets/94696121/04044e19-32aa-40ed-8549-81f2b412d25d)

**Comment by georgemoralis** [comment]
very nice but as it already stated on readme that compatibility list is for release versions only (at the time 0.1.0) i have to close it now...

**Comment by Brutal-sam** [comment]
tested it and it works the same with v0.1.0, I've edited the post.
