### ISSUE TITLE
KINGDOM HEARTS Ⅲ | Serial:CUSA12031 | Version:01.10 | not launching

### ISSUE THREAD

**Issue by SiriusVI87** [shadps4-emu/shadps4-game-compatibility#1330]
### Game Name

KINGDOM HEARTS Ⅲ

### Game code

CUSA12031

### Game version

v01.10

### Used emulator's version (only released versions are acceptable)

v0.4.0

### Current status

Nothing

### Operating System

Windows

### Error

"Failied to open descriptor file" [....] "TresGame.uproject"

### Description

When trying to launch the game, this error appears: "Failied to open descriptor file" [....] "TresGame.uproject".

Also happens in the newest Nightly version.

### Screenshots

![image](https://github.com/user-attachments/assets/af3685d7-bf0f-4262-8967-36523de6bc24)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18008105/shad_log.txt)

**Comment by Hermiten** [comment]
This one better and thanks you. But sorry again I didn't check before but it was already reported here:
https://github.com/shadps4-emu/shadps4-game-compatibility/issues/51
Please have a look if the game is already reported and in which version. For this game, someone already tried on 0.4. When the next release is up, you can comment your report on the other issue :)

**Comment by Hermiten** [comment]
Not work for this moment
