### ISSUE TITLE
CUSA07934 - Jak and Dexter - The Precursor Legacy

### ISSUE THREAD

**Issue by dajmodajmo** [shadps4-emu/shadps4-game-compatibility#1360]
### Game Name

Jak and Dexter - The Precursor Legacy

### Game code

CUSA07934

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.4.0

### Current status

Nothing

### Operating System

Windows

### Error

Does not boot

### Description

does not boot and emulator closes

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18067759/shad_log.txt)

**Comment by Hermiten** [comment]
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/378

**Comment by Hermiten** [comment]
You can update the test on the original one
