### ISSUE TITLE
CUSA05952 - Little Nightmares

### ISSUE THREAD

**Issue by SkarSM** [shadps4-emu/shadps4-game-compatibility#1365]
### Game Name

Little Nightmares

### Game code

CUSA05952

### Game version

1.07

### Used emulator's version (only released versions are acceptable)

0.4.1

### Current status

Boots

### Operating System

Windows

### Error

- Bootable but not functional.

### Description

It starts but shows a black screen, it does not reach the menu.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18086707/shad_log.txt)

**Comment by Hermiten** [comment]
Sorry, we only accept report on major release like 0.4

**Comment by SkarSM** [comment]
Sorry, I have already downloaded version 0.4.0 to try other games
