### ISSUE TITLE
CUSA06778 - Hidden Agenda

### ISSUE THREAD

**Issue by SkarSM** [shadps4-emu/shadps4-game-compatibility#1366]
### Game Name

Hidden Agenda

### Game code

CUSA06778 

### Game version

1.09

### Used emulator's version (only released versions are acceptable)

0.4.1

### Current status

Boots

### Operating System

Windows

### Error

- Bootable, but not functional

### Description

- The initial loading screen appears for about 5 seconds, then the emulator crashes.
- And it appears as if the version of the game was 01.00, when in reality it is 1.09.

### Screenshots

![c93f9d4c634fcac4b667d8b0df325d87](https://github.com/user-attachments/assets/5f847a2b-690c-4403-9588-7bc9fbe112fd)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18087133/shad_log.txt)

**Comment by thecatontheceiling** [comment]
"Used emulator's version (only released versions are acceptable)"
