### ISSUE TITLE
CUSA01766 - PROTOTYPE®

### ISSUE THREAD

**Issue by SkarSM** [shadps4-emu/shadps4-game-compatibility#1370]
### Game Name

PROTOTYPE®

### Game code

CUSA01766

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.4.0

### Current status

Menus

### Operating System

Windows

### Error

- Crashes after first cinematic

### Description

- Load up to the menus, let you select the difficulty, the initial cinematic appears with some pauses and at the end the emulator crashes.

- In the logs perhaps not everything appears since due to the maximum size allowed to upload the file I have to skip the cinematic.

### Screenshots

![03b63b54da5fe328b820b0b1de2a6fce](https://github.com/user-attachments/assets/23f3a06e-b15c-4745-9b2d-2adad6ad4196)
![b266dc44db731378a93df3448e2546aa](https://github.com/user-attachments/assets/d8f32ea9-c6ee-44da-bbe5-82ab7b306e00)
![02d4af01f5b5a456c8a121db45766de4](https://github.com/user-attachments/assets/279e9eda-7cca-4d6e-9298-21fd5ac52628)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18100461/shad_log.txt)

**Comment by Hermiten** [comment]
So for this one this is a duplaciate: Update it by a comment here:
https://github.com/shadps4-emu/shadps4-game-compatibility/issues/862
