### ISSUE TITLE
CUSA12982 - MediEvil

### ISSUE THREAD

**Issue by gabrielrjb** [shadps4-emu/shadps4-game-compatibility#1371]
### Game Name

MediEvil

### Game code

CUSA12982

### Game version

v01.02

### Used emulator's version (only released versions are acceptable)

v0.4.0

### Current status

Playable

### Operating System

Windows

### Error

Black screen and crashes.

### Description

It attempts to start, a black screen comes up after a second or two, then shadPS4 crashes entirely.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18106683/shad_log.txt)

**Comment by Hermiten** [comment]
Thanks but was done here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/82
