### ISSUE TITLE
CUSA33448 - Sophstar

### ISSUE THREAD

**Issue by 1manejoeyy** [shadps4-emu/shadps4-game-compatibility#1376]
### Game Name

Sophstar

### Game code

CUSA33448

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.41

### Current status

Playable

### Operating System

Windows

### Error

![log](https://github.com/user-attachments/assets/7a33cc69-bd15-450c-948b-0e03761c99de)

### Description

All modes have been tested and encountered 0 issues, game seems to be completely playable

### Screenshots

![Capture2](https://github.com/user-attachments/assets/b8672087-800e-4b3c-b5a5-ad0a896a270c)
![Capture3](https://github.com/user-attachments/assets/75a01ca6-4082-4a1d-a27c-d379b80f0f17)
![Capture4](https://github.com/user-attachments/assets/d1a678af-3fec-49de-a807-16f05cfa0a84)
![Capture6](https://github.com/user-attachments/assets/442ce703-dbce-4231-8b3d-83e92d578d5f)
![Capture](https://github.com/user-attachments/assets/f820d6dc-76a9-45ef-bd51-dd8e21d8e135)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18159294/shad_log.txt)

**Comment by C4ndyF1sh** [comment]
Only released versions are applicable (0.4.0)
