### ISSUE TITLE
CUSA32591 Deathsmiles 1&2 (Strictly Limited Version)

### ISSUE THREAD

**Issue by 1manejoeyy** [shadps4-emu/shadps4-game-compatibility#1377]
### Game Name

Deathsmiles 1&2

### Game code

CUSA32591

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.4.1

### Current status

Menus

### Operating System

Windows

### Error

![Capture1](https://github.com/user-attachments/assets/7d0b9d29-c811-4d4f-ae15-326cd193cde5)

### Description

game boots to the main menu but crashes when you choose which game to play

### Screenshots

![Capture](https://github.com/user-attachments/assets/ada78af8-b5e8-4ffa-9a20-a3fffd75dc61)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18159407/shad_log.txt)

**Comment by C4ndyF1sh** [comment]
only released versions are applicable (0.4.0)
