### ISSUE TITLE
The Forest

### ISSUE THREAD

**Issue by ThunderNowX** [shadps4-emu/shadps4-game-compatibility#1378]
### Game Name

The Forest

### Game code

CUSA12398

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.4.1

### Current status

Boots

### Operating System

Windows

### Error

[Debug] <Critical> memory.cpp:operator():694: Assertion Failed!

### Description

The game start at the first screen information, than crashes with this error:
[Debug] <Critical> memory.cpp:operator():694: Assertion Failed!
Exact build is: WIP main 8a4e032

### Screenshots

![TF](https://github.com/user-attachments/assets/5db88093-cdae-4118-bcaf-21e8a6b0cd38)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18163293/shad_log.txt)

**Comment by ThunderNowX** [comment]
if somebody can help with this, thanks!

**Comment by C4ndyF1sh** [comment]
only released versions are applicable (0.4.0)

**Comment by ThunderNowX** [comment]
Ok.. but why 0.4.1 pre release? Is not part of them?
0.4.0 is even worse, doesn't boot! Because it has got less progress than this, i guess i have to wait then
