### ISSUE TITLE
Grand Theft Auto III - The Definitive Edition

### ISSUE THREAD

**Issue by ThunderNowX** [shadps4-emu/shadps4-game-compatibility#1379]
### Game Name

Grand Theft Auto III - The Definitive Edition

### Game code

CUSA23501

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.4.1

### Current status

Menus

### Operating System

Windows

### Error

[Debug] <Critical> scalar_alu.cpp:operator():606: Unreachable code!

### Description

While starting a new game, at first screen loading, crashes with Unreachable code!

### Screenshots

![Screenshot 2024-12-17 184319](https://github.com/user-attachments/assets/cb0f8787-d530-4035-965f-c693930fdb56)
![Screenshot 2024-12-17 184530](https://github.com/user-attachments/assets/e5f30fd6-c999-4fda-b73d-a130fd96655e)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18169465/shad_log.txt)

**Comment by C4ndyF1sh** [comment]
only released versions are applicable (0.4.0)

**Comment by ThunderNowX** [comment]
Ok.. but why 0.4.1 pre release? Is not part of them?
0.4.0 is even worse, doesn't boot! Because it has got less progress than this, i guess i have to wait then

**Comment by C4ndyF1sh** [comment]
![image](https://github.com/user-attachments/assets/9a287bfb-205d-426a-925c-557cde53d856)

**Comment by ThunderNowX** [comment]
Ok, let me fix then!
Let me try 0.4.0
