### ISSUE TITLE
Brick Breaker

### ISSUE THREAD

**Issue by AussiePlick** [shadps4-emu/shadps4-game-compatibility#1385]
### Game Name

Brick Breaker

### Game code

CUSA03889

### Game version

1.00

### Used emulator's version (only released versions are acceptable)

v041 WIP Pre Release

### Current status

Boots

### Operating System

Windows

### Error

Black Screen, with perfect audio.

### Description

Boots to Black screen and perfect audio, 

### Screenshots

![Brick-Breaker](https://github.com/user-attachments/assets/6f8e1609-cdd4-4ceb-a45a-d7f9afc85d1a)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18196965/shad_log.txt)

**Comment by Hermiten** [comment]
We only accept tet on major release (0.4 for example) thanks you
