### ISSUE TITLE
BoxVR

### ISSUE THREAD

**Issue by AussiePlick** [shadps4-emu/shadps4-game-compatibility#1386]
### Game Name

BoxVR

### Game code

CUSA14578

### Game version

1.04

### Used emulator's version (only released versions are acceptable)

0.4.1 WIP Pre Release

### Current status

Nothing

### Operating System

Windows

### Error

Black screen and no audio. Crashes and freezes after 15 seconds.

### Description

Black screen and no audio. Crashes after 30 seconds.

### Screenshots

![BoxVR](https://github.com/user-attachments/assets/4fc69c3a-cf9b-45f9-b458-9eca2b68b8c5)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18197072/shad_log.txt)

**Comment by ThunderNowX** [comment]
Only released are acceptable
31 Oct was latest stable release, so you have to generate log using 0.4.0 it was latest stable releass, they mean them that is acceptable, pre-release is still under dev, so not yet stable and not yet released fully

**Comment by Hermiten** [comment]
We only accept tet on major release (0.4 for example) thanks you

**Comment by AussiePlick** [comment]
OK. I will redo when I get a chance with major release.
