### ISSUE TITLE
Render issue

### ISSUE THREAD

**Issue by iodor** [shadps4-emu/shadps4-game-compatibility#1394]
### Game Name

Bloodborne

### Game code

CUSA03173

### Game version

1.09

### Used emulator's version (only released versions are acceptable)

V0.4.1

### Current status

Ingame

### Operating System

Windows

### Error

Problem with rendering, see the screenshot

### Description

RTX 4070 super
AMD ryzen 5 7500F

### Screenshots

![photo_2024-12-20_15-11-27](https://github.com/user-attachments/assets/54f38cac-d2e6-4b0f-b7b9-79d45e619f62)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18211671/shad_log.txt)

**Comment by ThunderNowX** [comment]
Bro, you have to use 0.4.0 to report issues
Only acceptable version released, no WIP builds, 0.4.1 is still prerelease not release

**Comment by Hermiten** [comment]
Please read the rules before opening a report
