### ISSUE TITLE
Love Live! School Idol Festival ~after school ACTIVITY~ Wai-Wai!Home Meeting!! 100%

### ISSUE THREAD

**Issue by Carrizo1821** [shadps4-emu/shadps4-game-compatibility#1401]
### Game Name

Love Live! School Idol Festival ~after school ACTIVITY~ Wai-Wai!Home Meeting!!

### Game code

CUSA24620

### Game version

v01.02

### Used emulator's version (only released versions are acceptable)

v0.4.1 WIP

### Current status

Playable

### Operating System

Windows

### Error

It just has some texture bugs but it doesn't bother the gameplay

### Description

The game works well, I had no problems playing.

### Screenshots

![Captura de pantalla 2024-12-20 233728](https://github.com/user-attachments/assets/af936b6e-4bf7-4627-847d-7a9fa8ad4e16)
![Captura de pantalla 2024-12-20 233808](https://github.com/user-attachments/assets/322779ea-e460-40d5-acb6-dd95e9deb0f2)
![Captura de pantalla 2024-12-20 233831](https://github.com/user-attachments/assets/902598f3-3db5-4a9c-9c9c-f6f6499a1996)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18216941/shad_log.txt)

**Comment by Carrizo1821** [comment]
os-windows status-playable

**Comment by Carrizo1821** [comment]
https://github.com/shadps4-emu/shadps4-game-compatibility/labels/os-windows
https://github.com/shadps4-emu/shadps4-game-compatibility/labels/status-playable

**Comment by C4ndyF1sh** [comment]
only major releases are allowed (0.4.0)
