### ISSUE TITLE
CUSA18093 - 十三機兵防衛圈

### ISSUE THREAD

**Issue by kukufeng** [shadps4-emu/shadps4-game-compatibility#1425]
### Game Name

十三機兵防衛圈

### Game code

CUSA18093

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.4.1 WIP

### Current status

Playable

### Operating System

Windows

### Error

The game runs without errors

### Description

The game runs perfectly without any errors, and the frame rate is 60 throughout the game

### Screenshots

![HYU_ZO}X2_TVR `~8)L@3(D](https://github.com/user-attachments/assets/b8957940-65f1-4142-963e-92082aef726c)

### Log File

[shadPS4.20241225-100653-528.log](https://github.com/user-attachments/files/18246182/shadPS4.20241225-100653-528.log)

**Comment by Hermiten** [comment]
Hello, we only accept report on major release, the last one is 0.4. Thanks you !
