### ISSUE TITLE
CUSA01623 - God of War® III Remastered

### ISSUE THREAD

**Issue by ThunderNowX** [shadps4-emu/shadps4-game-compatibility#1432]
### Game Name

God of War® III Remastered

### Game code

CUSA01623

### Game version

01.02

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Playable

### Operating System

Windows

### Error

Crashes with Unreachable code!

### Description

Just horrible, not working, like 0.4.0

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18247215/shad_log.txt)

**Comment by Hermiten** [comment]
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/323

**Comment by ThunderNowX** [comment]
[shad_log_gow3rm.txt](https://github.com/user-attachments/files/18247260/shad_log_gow3rm.txt)
0.5.0 GoWIII

**Comment by Hermiten** [comment]
Update here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/323
Not on this one (#1432)
