### ISSUE TITLE
CUSA08355 - Shenmue

### ISSUE THREAD

**Issue by DLADAnaconda** [shadps4-emu/shadps4-game-compatibility#1463]
### Game Name

Shenmue

### Game code

CUSA08355

### Game version

01.03

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Nothing

### Operating System

Windows

### Error

Crashes to desktop on boot, with or without updates and DLCs

### Description

Crashes to desktop on boot, with or without updates and DLCs

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18248433/shad_log.txt)

**Comment by Hermiten** [comment]
Duplicate of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1240

**Comment by Hermiten** [comment]
Please update by a comment here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1240
