### ISSUE TITLE
CUSA42936 - Double Dragon Gaiden: Rise of the Dragons

### ISSUE THREAD

**Issue by alx5962** [shadps4-emu/shadps4-game-compatibility#1505]
### Game Name

Double Dragon Gaiden: Rise of the Dragons

### Game code

CUSA42936

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.1 WIP

### Current status

Nothing

### Operating System

Windows

### Error

Crash emulator

### Description

game is launched then shadps4 crashes.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18253149/shad_log.txt)

**Comment by C4ndyF1sh** [comment]
WIP versions are not allowed on the compatibility list

**Comment by Hermiten** [comment]
Only major release like 0.5.0
