### ISSUE TITLE
CUSA05362 - Ronin

### ISSUE THREAD

**Issue by alx5962** [shadps4-emu/shadps4-game-compatibility#1506]
### Game Name

Ronin

### Game code

CUSA05362

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.1 WIP

### Current status

Playable

### Operating System

Windows

### Error

Nothing

### Description

I played 3-5mn without errors or glitches.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18253172/shad_log.txt)

**Comment by C4ndyF1sh** [comment]
WIP versions are not allowed on the compatibility list

**Comment by Hermiten** [comment]
Only major release like 0.5.0
