### ISSUE TITLE
CUSA20601 - Spelunky 2

### ISSUE THREAD

**Issue by alx5962** [shadps4-emu/shadps4-game-compatibility#1507]
### Game Name

Spelunky 2

### Game code

CUSA20601

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.1 WIP

### Current status

Boots

### Operating System

Windows

### Error

Boots then the game loops at loading before the splash screen.

### Description

The first loading screen has a rotating logo but text is garbage. Waited many minutes but doesn't go further.

### Screenshots

![image](https://github.com/user-attachments/assets/3f49e1c2-f75f-435d-91b5-97430e30fe42)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18253218/shad_log.txt)

**Comment by C4ndyF1sh** [comment]
WIP versions are not allowed on the compatibility list
