### ISSUE TITLE
CUSA33956 - Task Force Delta - Afghanistan

### ISSUE THREAD

**Issue by Quaii** [shadps4-emu/shadps4-game-compatibility#1515]
### Game Name

Task Force Delta - Afghanistan

### Game code

CUSA33956

### Game version

01.01

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Nothing

### Operating System

Windows

### Error

not playable only shows a black screen

### Description

just a black screen 

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18254270/shad_log.txt)

**Comment by Hermiten** [comment]
Same here https://github.com/shadps4-emu/shadps4-game-compatibility/issues/659
