### ISSUE TITLE
CUSA03173 - Bloodborne™

### ISSUE THREAD

**Issue by beelzebud** [shadps4-emu/shadps4-game-compatibility#1516]
### Game Name

Bloodborne™

### Game code

CUSA03173

### Game version

01.09

### Used emulator's version (only released versions are acceptable)

0.5.1 WIP

### Current status

Playable

### Operating System

Windows

### Error

There are still some vertex explosions that can happen after player dies and comes back.   Tested on Nvidia Geforce 3060RTX, with driver version 566.36, on Windows 11 Pro version 23H2.

### Description

The game looks great,  and is running smooth.

### Screenshots

![bloodborne_02](https://github.com/user-attachments/assets/ae04229b-fb39-4002-971b-c3ce35b767b5)
![bloodborne_01](https://github.com/user-attachments/assets/e18bc559-ec01-4e65-9e5c-b32116b3e6d6)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18254478/shad_log.txt)

**Comment by Xphalnos** [comment]
Only stable versions are allowed and bloodborne has already been referenced. Thanks!
