### ISSUE TITLE
SLES53552 - SSX On Tour [EU] [FiXed]

### ISSUE THREAD

**Issue by DLADAnaconda** [shadps4-emu/shadps4-game-compatibility#1523]
### Game Name

SSX On Tour [EU] [FiXed]

### Game code

SLES53552

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Nothing

### Operating System

Windows

### Error

Crashes to desktop on boot

### Description

Crashes to desktop on boot

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18255620/shad_log.txt)

**Comment by Xphalnos** [comment]
Cannot be considered valid because it is the game data that is corrupted.

`[Loader] <Info> elf.cpp:IsElfFile:260: Not an ELF file magic is wrong!`
`[Core.Linker] <Error> linker.cpp:LoadModule:106: Provided file D:/Games/Consoles/SHAD/SLES53552\sce_module\libSceFios2.prx is not valid ELF file`

**Comment by DLADAnaconda** [comment]
Ok, interesting, I would be curious if it would work on a real PS4, since the claims are that it plays considering you said there is an error in the build.

**Comment by DLADAnaconda** [comment]
> Cannot be considered valid because it is the game data that is corrupted.
> 
> `[Loader] <Info> elf.cpp:IsElfFile:260: Not an ELF file magic is wrong!` `[Core.Linker] <Error> linker.cpp:LoadModule:106: Provided file D:/Games/Consoles/SHAD/SLES53552\sce_module\libSceFios2.prx is not valid ELF file`

Ok, interesting, I would be curious if it would work on a real PS4, since the claims are that it plays considering you said there is an error in the build.
