### ISSUE TITLE
SLUS20159 - Dave Mirra Freestyle BMX 2 [US] [WS] [FiXed]

### ISSUE THREAD

**Issue by DLADAnaconda** [shadps4-emu/shadps4-game-compatibility#1527]
### Game Name

Dave Mirra Freestyle BMX 2 [US] [WS] [FiXed]

### Game code

SLUS20159

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Nothing

### Operating System

Windows

### Error

Game crashes on boot

### Description

Game crashes on boot

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18255803/shad_log.txt)

**Comment by Xphalnos** [comment]
Cannot be considered valid because it is the game data that is corrupted.

`[Core.Linker] <Error> linker.cpp:LoadModule:106: Provided file D:/Games/Consoles/SHAD/SLUS20335\sce_module\libSceFios2.prx is not valid ELF file`
`[Loader] <Info> elf.cpp:IsElfFile:260: Not an ELF file magic is wrong!`

**Comment by DLADAnaconda** [comment]
> Cannot be considered valid because it is the game data that is corrupted.
> 
> `[Core.Linker] <Error> linker.cpp:LoadModule:106: Provided file D:/Games/Consoles/SHAD/SLUS20335\sce_module\libSceFios2.prx is not valid ELF file` `[Loader] <Info> elf.cpp:IsElfFile:260: Not an ELF file magic is wrong!`

Ok, interesting, I would be curious if it would work on a real PS4, since the claims are that it plays considering you said there is an error in the build.
