### ISSUE TITLE
CUSA02703 - Mad Max

### ISSUE THREAD

**Issue by PistolaoBR** [shadps4-emu/shadps4-game-compatibility#1543]
### Game Name

Mad Max

### Game code

CUSA02703

### Game version

v01.06

### Used emulator's version (only released versions are acceptable)

v0.5.0

### Current status

Nothing

### Operating System

Windows

### Error

It does not install on the emulator. It says that it is a file with just the update, not the main game, asking to install the game first than the update, the version CUSA02703 does not have a v01.00, just the one with update applied 

### Description

Cannot install the game file, the emulator mistake as just the update

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18256959/shad_log.txt)

**Comment by Xphalnos** [comment]
This report cannot be considered valid because the log is empty and it is rather an installation problem.
