### ISSUE TITLE
CUSA32336 - Blade Runner: Enhanced Edition

### ISSUE THREAD

**Issue by Baldyshugga** [shadps4-emu/shadps4-game-compatibility#1545]
### Game Name

Blade Runner: Enhanced Edition

### Game code

CUSA32336

### Game version

01.03

### Used emulator's version (only released versions are acceptable)

0.5.1 WIP

### Current status

Ingame

### Operating System

Windows

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceSystemGestureUpdatePrimitiveTouchRecognizer (nid: GgFMb22sbbI) called, returning zero to 0x9001ad1b8
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceSystemGestureUpdateAllTouchRecognizer (nid: wPJGwI2RM2I) called, returning zero to 0x9001ad1cf
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceSystemGestureGetTouchEventsCount (nid: h8uongcBNVs) called, returning zero to 0x9001ae352
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceSystemGestureGetTouchEventsCount (nid: h8uongcBNVs) called, returning zero to 0x9001ae352
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceSystemGestureGetTouchEventsCount (nid: h8uongcBNVs) called, returning zero to 0x9001ae352
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceSystemGestureGetTouchEventsCount (nid: h8uongcBNVs) called, returning zero to 0x9001ae352
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceSystemGestureGetTouchEventsCount (nid: h8uongcBNVs) called, returning zero to 0x9001ae352
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceMouseRead (nid: x8qnXqh-tiM) called, returning zero to 0x9001adbc9
[Lib.Ngs2] <Error> ngs2.cpp:sceNgs2SystemRender:229: (STUBBED) called

### Description

Works well except the text box is missing or disappears very fast. Also the vocal audio is missing.

### Screenshots

![shadPS4 v0 5 1 WIP main edc027a _ CUSA32336 - Blade Runner_ Enhanced Edition _01 03_ 12_26_2024 10_56_02 PM](https://github.com/user-attachments/assets/db67bafa-c0e0-43c0-82f0-aa509efa824c)
![shadPS4 v0 5 1 WIP main edc027a _ CUSA32336 - Blade Runner_ Enhanced Edition _01 03_ 12_26_2024 11_00_02 PM](https://github.com/user-attachments/assets/fa081dbd-3baa-40be-b2e2-8e75b317185d)
![shadPS4 v0 5 1 WIP main edc027a _ CUSA32336 - Blade Runner_ Enhanced Edition _01 03_ 12_26_2024 11_00_16 PM](https://github.com/user-attachments/assets/97568d7a-473f-4508-b29d-1399047c4bbe)
![shadPS4 v0 5 1 WIP main edc027a _ CUSA32336 - Blade Runner_ Enhanced Edition _01 03_ 12_26_2024 11_00_37 PM](https://github.com/user-attachments/assets/ae76b248-0f47-4182-86f5-00f4124db1c6)

### Log File

[Uploading shad_log.txt…]()

**Comment by Xphalnos** [comment]
Only stable versions are allowed! (v0.5.0)
