### ISSUE TITLE
CUSA36842 - Red Dead Redemption

### ISSUE THREAD

**Issue by PistolaoBR** [shadps4-emu/shadps4-game-compatibility#1561]
### Game Name

Red Dead Redemption

### Game code

CUSA36842

### Game version

v01.00 v01.04

### Used emulator's version (only released versions are acceptable)

v0.5.0

### Current status

Ingame

### Operating System

Windows

### Error

White noise plays nonstop
Some os the NPCs don't render

### Description

White noise plays nonstop
Some os the NPCs don't render

### Screenshots

![image](https://github.com/user-attachments/assets/a3269e77-cfde-47c9-9a90-f178de8012ae)
![image](https://github.com/user-attachments/assets/58c8e572-8876-4c99-9119-0c8576aca9c1)
![image](https://github.com/user-attachments/assets/d9e1ad8a-f949-4b92-b0df-8277fef4c1e4)
![image](https://github.com/user-attachments/assets/262e0b6c-fe04-4a8e-9198-807f8d3ba7a5)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18260914/shad_log.txt)

**Comment by Xphalnos** [comment]
Duplicated of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1390.
