### ISSUE TITLE
CUSA03173 - Bloodborne™

### ISSUE THREAD

**Issue by TafsirFaiyaz** [shadps4-emu/shadps4-game-compatibility#1564]
### Game Name

Bloodborne™

### Game code

CUSA03173

### Game version

01.09

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Ingame

### Operating System

Windows

### Error

![Screenshot (3404)](https://github.com/user-attachments/assets/cebe01a9-26ad-411e-9974-09a9b0b383f9)

### Description

Everytime I try to open the door the game freezes and crash. The door is in the lecture hall and used to go to Nightmare of Mensis area. Everytime I try to open the door the game crash

### Screenshots

![Screenshot (3404)](https://github.com/user-attachments/assets/6308c89a-9a9c-4909-ac31-d39e5eed5970)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18261622/shad_log.txt)

**Comment by Xphalnos** [comment]
Duplicated.

**Comment by TafsirFaiyaz** [comment]
> Duplicated.

Can you elaborate what do you mean by duplicate

**Comment by Xphalnos** [comment]
> > Duplicated.
> 
> Can you elaborate what do you mean by duplicate

This is duplicated from https://github.com/shadps4-emu/shadps4-game-compatibility/issues/71
