### ISSUE TITLE
CUSA08692 - Dark Souls Remastered

### ISSUE THREAD

**Issue by PistolaoBR** [shadps4-emu/shadps4-game-compatibility#1568]
### Game Name

Dark Souls Remastered

### Game code

CUSA08692

### Game version

v01.00 v01.03

### Used emulator's version (only released versions are acceptable)

v0.5.0

### Current status

Playable

### Operating System

Windows

### Error

Runs fine without any problems

### Description

Runs fine without any problems

### Screenshots

![image](https://github.com/user-attachments/assets/63c21aac-c704-43f2-b3c4-0ebac00d1074)
![image](https://github.com/user-attachments/assets/85cdecba-3fa8-423a-a0bb-7a3788cd48ab)
![image](https://github.com/user-attachments/assets/88b028ab-a3e6-45a9-a52f-beb3bac16d9d)
![image](https://github.com/user-attachments/assets/d061210e-f39b-4a63-b159-865919999841)
![image](https://github.com/user-attachments/assets/f84cd58a-6266-4e3e-bd6c-37330f19f4c0)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18262453/shad_log.txt)

**Comment by Xphalnos** [comment]
Duplicated of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/191.

**Comment by Xphalnos** [comment]
Remember to check that the report does not already exist. Thank you.

**Comment by PistolaoBR** [comment]
> Remember to check that the report does not already exist. Thank you.

but that one says that the game is unplayable

**Comment by Xphalnos** [comment]
> > Remember to check that the report does not already exist. Thank you.
> 
> but that one says that the game is unplayable

This is because it was tested on an older version but now it is playable.

**Comment by PistolaoBR** [comment]
> > > Remember to check that the report does not already exist. Thank you.
> > 
> > 
> > but that one says that the game is unplayable
> 
> This is because it was tested on an older version but now it is playable.

Yes, I understand that, that is the why I redid the test... However, even if you change the status from in-game to playable [Xphalnos](https://github.com/Xphalnos) the game doesnt show as playable on https://shadps4.emutube.com/

**Comment by Xphalnos** [comment]
> > > > Remember to check that the report does not already exist. Thank you.
> > > 
> > > 
> > > but that one says that the game is unplayable
> > 
> > 
> > This is because it was tested on an older version but now it is playable.
> 
> Yes, I understand that, that is the why I redid the test... However, even if you change the status from in-game to playable [Xphalnos](https://github.com/Xphalnos) the game doesnt show as playable on https://shadps4.emutube.com/

Bruh, it must be due to the refresh time
![image](https://github.com/user-attachments/assets/26f7301d-d505-43dc-950d-c1208212c904)

**Comment by PistolaoBR** [comment]
> Bruh, it must be due to the refresh time !

Try to mark v on playable filter... only games that start as playable will show, all others that changed it status from anything to playable wont show @Xphalnos 

![image](https://github.com/user-attachments/assets/abd4dae1-4101-4e00-9e60-26f0b5f046cf)
