### ISSUE TITLE
Shadow of the Colossus crashes on V0.1.0

### ISSUE THREAD

**Issue by Epic3Drago** [shadps4-emu/shadps4-game-compatibility#157]
### Game Name

Shadow of the Colossus

### Game code

CUSA08809

### Game version

v01.01

### Used emulator's version (only released versions are acceptable)

shadps4 v0.1.0 codename madturtle

### Current status

Nothing

### Error

Check log for Emulation Crash error trying to boot the game.

### Description

Game tries to boot but stays on **black screen** and crashes the emulator.  _"Assertion Failed; Cannot load already loaded maps."_

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16158908/shad_log.txt)

**Comment by georgemoralis** [comment]
game already tested and according to log you are using v0.1.1 WIP , only release versions permitted
