### ISSUE TITLE
CUSA02046 - Godzilla

### ISSUE THREAD

**Issue by Logzombie** [shadps4-emu/shadps4-game-compatibility#1570]
### Game Name

Godzilla

### Game code

CUSA02046

### Game version

v1.01

### Used emulator's version (only released versions are acceptable)

v0.5.0

### Current status

Ingame

### Operating System

Windows

### Error

page_manager.cpp:operator():207: Assertion Failed!
Attempted to track non-GPU memory at address 0x14b8e2000, size 0xfe000.

### Description

Game will boot, until intro cutscene is loaded. Game requires cutscenes to be removed in order to avoid crash on startup when attempting to load pre-rendered MP4 files in the PKG install directory. (See assertion failure above.)

Once cutscenes are removed, game will skip cutscenes, is able to reach main menu and is able to proceed into the tutorial. All audio ASIDE from language based spoken dialogue will load. All language spoken dialogue is skipped, and will be completely silent, as if voice volume is turned off.

Game will proceed to softlock during tutorial, (POTENTIALLY) due to the above issue. Tutorial will hang, waiting for G-Force Operator to stop talking before proceeding with gameplay, but no voice lines are loaded and thus game seems to wait indefinitely before proceeding with her next lines, getting stuck. In other modes, her text box will become stuck on screen, or not appear at all.

Most menu options are missing text, but are navigable due to text hints in other fonts and imagery on the right side of the screen.

A save file is required in order to bypass the required tutorial. In which the following gamemodes will have these effects:
**King of Kaiju mode:** 100% playable with seemingly 0 issues.
**God of Destruction (Go Ashore):** Softlocks on opening cutscene due to same reason as tutorial.
**God of Destruction (Invade):** Skip feature will appear during opening cutscene, and able to proceed into gameplay. G-Force Op will become stuck however, and no additional military squads or monsters will spawn until Stage 3, where her behaviour seemingly returns to normal.
**God of Destruction (Defend):** Softlocks on opening cutscene due to same reason as tutorial.
**Vs Mode:** No online features supported yet, so this obviously won't work. Theoretically, G-Force Op bug will likely not intrude on this mode even if there were.
**Diorama mode:** Seems to work fine(?), not tested enough as this mode is simply made to create screenshots.
**Evolution mode:** Works, but all text is missing so you have NO idea what you're upgrading on your characters.

Ironically, upon completing two stages of God of Destruction (Invade), the G-Force Operator will begin behaving as normal (albiet without any audible spoken dialogue still) once entering Stage 3, and as a result, gameplay resumes entirely as it should. **Including in other modes, which technically makes the game 100% playable without softlocks.** That is until the game is closed and re-launched, requiring 2 stages of God of Destruction (Invade) to be completed again to evade this bug. 

No Major graphical or audio based issues aside from language dialogue at least that I can see thus far. Game performance is pristine, Consistent 60 FPS with seemingly little dips in it's actual performance. Has only crashed once after multiple playthroughs outputting no error into the log, nor closing the emulator. Seemingly locked up while still playing looping audio and music. Possibly not related to ShadPS4. Unable to replicate.

If it weren't for G-Force Op's dialogue issue requiring circumvention (and I have NO idea why it consistently has this fix), the game would be seemingly playable entirely, as once circumventing this issue, start to finish playthroughs of God of Destruction mode (including story mode, aka Go Ashore, and King of Kaiju mode even without circumvention) are stable and possible.

### Screenshots

![shadPS4_QYkzIL56FZ](https://github.com/user-attachments/assets/b08747f3-5de7-4f77-8658-fa5897af5623)
![shadPS4_XZ2ol8KzRL](https://github.com/user-attachments/assets/7d5a37bb-f04b-4d9e-9747-07863e525d5f)
![shadPS4_g3R9MXK6JP](https://github.com/user-attachments/assets/85d573ad-7b51-4fb1-93c4-a78646b8a424)
![shadPS4_Av68lG31au](https://github.com/user-attachments/assets/da3e4d05-a3f6-4472-9cb1-83bdbbd69e09)
![shadPS4_IIgOIH3uW7](https://github.com/user-attachments/assets/867235d8-ca50-457c-b2d9-87e2fc051a8b)
![shadPS4_LUnxAHlu9K](https://github.com/user-attachments/assets/25b1601f-8ccd-484d-9a6f-5a2433d2b2f4)
![Base Profile Screenshot 2024 12 26 - 23 26 05 19](https://github.com/user-attachments/assets/9bc43146-0fb1-47a4-86a7-b9c721b142ff)

### Log File

Cutscenes removed, 1 stage worth of God of Destruction gameplay: [shad_log.txt](https://github.com/user-attachments/files/18262520/shad_log.txt)

**Comment by Xphalnos** [comment]
Duplicated from https://github.com/shadps4-emu/shadps4-game-compatibility/issues/565
You can update the status by commenting on this report.

**Comment by Brooks3000** [comment]
Hey, what are the names of all the files you need to delete in order for the game to run, and could you please provide their location?

**Comment by Logzombie** [comment]
> Hey, what are the names of all the files you need to delete in order for the game to run, and could you please provide their location?

In the install directory of the game, the cutscenes are stored as .MP4 files. Simply remove all .MP4 files from the game's directory.

**Comment by MrDorkian** [comment]
Got it, thanks

**Comment by MrDorkian** [comment]
Sorry to be asking another question, but I'm trying to replace a my base save file with a 90% save file for the game, yet no matter what I do the game will either say that I need to create more data or I will be forced into the tutorial and softlocked. Could you please help?

**Comment by adamblue83** [comment]
Hello, this is great progress. One interesting issue for me is no sound. Maybe I can continue to troubleshoot. But, anyone have a save file at that stage 3 of invade? Thank you.

**Comment by Logzombie** [comment]
> Hello, this is great progress. One interesting issue for me is no sound. Maybe I can continue to troubleshoot. But, anyone have a save file at that stage 3 of invade? Thank you.

In order for audio to function, you must make sure that you have your PS4 System Modules correctly installed into ShadPS4, else no audio will load, and certain crashes are likely to occur.

**Comment by jasuso2** [comment]
Hi! Any chance you could share your save file to bypass the prologue bug?, I cant get to work the 100% save files I found in the internet

**Comment by jasuso2** [comment]
> Sorry to be asking another question, but I'm trying to replace a my base save file with a 90% save file for the game, yet no matter what I do the game will either say that I need to create more data or I will be forced into the tutorial and softlocked. Could you please help?

Did you managed to fix it? I´m also trying to import a save to bypass the issue

**Comment by MrDorkian** [comment]
> > Sorry to be asking another question, but I'm trying to replace a my base save file with a 90% save file for the game, yet no matter what I do the game will either say that I need to create more data or I will be forced into the tutorial and softlocked. Could you please help?
> 
> Did you managed to fix it? I´m also trying to import a save to bypass the issue

Not yet, I've been waiting for a response

**Comment by Zanosfr** [comment]
Here is the save file. Got it from here https://www.thetechgame.com/Downloads/id=234516/eu-godzilla-platinum-game-save-cusa02058.html and just decrypted it. if you wanna know how to decrypt your files look at this video https://www.youtube.com/watch?v=UUPi_jHerWI
Here is the discord as well (when you're in the discord use bot 9 none of the bots work rn I think)
https://discord.gg/nRHAhMDr
(save is the drive)
https://drive.google.com/drive/folders/1m2SVrI6UKFJEKDKFFS1-GzY5B_L2uO0Z?usp=drive_link
Hope this helps
(Go to \user\savedata\1\CUSA02046 and replace the SAVEDATA00 with the one I gave you)
if you don't understand what the guy is saying in the video just add me on Discord and I'll help @callemzanos)

How are yall able to get yalls to load and play? Mines just opens the gamemode and then crashes on the loading screen?

**Comment by TheIronWolfx119** [comment]
So it's letting you use a save file from the EU version with the NA version of the game? You didn't have to resign it or anything?

**Comment by jasuso2** [comment]
Now the game is running but a new bug i found is that godzilla cant move, it somehow mutes the lady that talks in the prologue but now i cant move at all, I will try using a ps4 controller and see how it goes

**Comment by jasuso2** [comment]
> Here is the save file. Got it from here https://www.thetechgame.com/Downloads/id=234516/eu-godzilla-platinum-game-save-cusa02058.html and just decrypted it. if you wanna know how to decrypt your files look at this video https://www.youtube.com/watch?v=UUPi_jHerWI Here is the discord as well (when you're in the discord use bot 9 none of the bots work rn I think) https://discord.gg/nRHAhMDr (save is the drive) https://drive.google.com/drive/folders/1m2SVrI6UKFJEKDKFFS1-GzY5B_L2uO0Z?usp=drive_link Hope this helps (Go to \user\savedata\1\CUSA02046 and replace the SAVEDATA00 with the one I gave you) if you don't understand what the guy is saying in the video just add me on Discord and I'll help @callemzanos)
> 
> How are yall able to get yalls to load and play? Mines just opens the gamemode and then crashes on the loading screen?

It didnt worked :0 still tells me to create a new save

**Comment by Zanosfr** [comment]
> > Here is the save file. Got it from here https://www.thetechgame.com/Downloads/id=234516/eu-godzilla-platinum-game-save-cusa02058.html and just decrypted it. if you wanna know how to decrypt your files look at this video https://www.youtube.com/watch?v=UUPi_jHerWI Here is the discord as well (when you're in the discord use bot 9 none of the bots work rn I think) https://discord.gg/nRHAhMDr (save is the drive) https://drive.google.com/drive/folders/1m2SVrI6UKFJEKDKFFS1-GzY5B_L2uO0Z?usp=drive_link Hope this helps (Go to \user\savedata\1\CUSA02046 and replace the SAVEDATA00 with the one I gave you) if you don't understand what the guy is saying in the video just add me on Discord and I'll help @callemzanos)
> > How are yall able to get yalls to load and play? Mines just opens the gamemode and then crashes on the loading screen?
> 
> It didnt worked :0 still tells me to create a new save

DId you delete your other save?

**Comment by Zanosfr** [comment]
> > > Here is the save file. Got it from here https://www.thetechgame.com/Downloads/id=234516/eu-godzilla-platinum-game-save-cusa02058.html and just decrypted it. if you wanna know how to decrypt your files look at this video https://www.youtube.com/watch?v=UUPi_jHerWI Here is the discord as well (when you're in the discord use bot 9 none of the bots work rn I think) https://discord.gg/nRHAhMDr (save is the drive) https://drive.google.com/drive/folders/1m2SVrI6UKFJEKDKFFS1-GzY5B_L2uO0Z?usp=drive_link Hope this helps (Go to \user\savedata\1\CUSA02046 and replace the SAVEDATA00 with the one I gave you) if you don't understand what the guy is saying in the video just add me on Discord and I'll help @callemzanos)
> > > How are yall able to get yalls to load and play? Mines just opens the gamemode and then crashes on the loading screen?
> > 
> > 
> > It didnt worked :0 still tells me to create a new save
> 
> DId you delete your other save?

I'll make a video and send it to you once I settle down

**Comment by jasuso2** [comment]
> > > > Here is the save file. Got it from here https://www.thetechgame.com/Downloads/id=234516/eu-godzilla-platinum-game-save-cusa02058.html and just decrypted it. if you wanna know how to decrypt your files look at this video https://www.youtube.com/watch?v=UUPi_jHerWI Here is the discord as well (when you're in the discord use bot 9 none of the bots work rn I think) https://discord.gg/nRHAhMDr (save is the drive) https://drive.google.com/drive/folders/1m2SVrI6UKFJEKDKFFS1-GzY5B_L2uO0Z?usp=drive_link Hope this helps (Go to \user\savedata\1\CUSA02046 and replace the SAVEDATA00 with the one I gave you) if you don't understand what the guy is saying in the video just add me on Discord and I'll help @callemzanos)
> > > > How are yall able to get yalls to load and play? Mines just opens the gamemode and then crashes on the loading screen?
> > > 
> > > 
> > > It didnt worked :0 still tells me to create a new save
> > 
> > 
> > DId you delete your other save?
> 
> I'll make a video and send it to you once I settle down

Yes I deleted my old save, also trying just overwriting, please it will help many people who are also trying to get the game to function if you share a video of your process, are you using the nightly build? you can get into king of kaiju mode with version v5.0

**Comment by Zanosfr** [comment]
> > > > > Here is the save file. Got it from here https://www.thetechgame.com/Downloads/id=234516/eu-godzilla-platinum-game-save-cusa02058.html and just decrypted it. if you wanna know how to decrypt your files look at this video https://www.youtube.com/watch?v=UUPi_jHerWI Here is the discord as well (when you're in the discord use bot 9 none of the bots work rn I think) https://discord.gg/nRHAhMDr (save is the drive) https://drive.google.com/drive/folders/1m2SVrI6UKFJEKDKFFS1-GzY5B_L2uO0Z?usp=drive_link Hope this helps (Go to \user\savedata\1\CUSA02046 and replace the SAVEDATA00 with the one I gave you) if you don't understand what the guy is saying in the video just add me on Discord and I'll help @callemzanos)
> > > > > How are yall able to get yalls to load and play? Mines just opens the gamemode and then crashes on the loading screen?
> > > > 
> > > > 
> > > > It didnt worked :0 still tells me to create a new save
> > > 
> > > 
> > > DId you delete your other save?
> > 
> > 
> > I'll make a video and send it to you once I settle down
> 
> Yes I deleted my old save, also trying just overwriting, please it will help many people who are also trying to get the game to function if you share a video of your process, are you using the nightly build? you can get into king of kaiju mode with version v5.0

https://youtu.be/Vl_dX2lUG7s
and yeah I'm going to switch to 5.0 and see if it works

**Comment by jasuso2** [comment]
> > > > > > Here is the save file. Got it from here https://www.thetechgame.com/Downloads/id=234516/eu-godzilla-platinum-game-save-cusa02058.html and just decrypted it. if you wanna know how to decrypt your files look at this video https://www.youtube.com/watch?v=UUPi_jHerWI Here is the discord as well (when you're in the discord use bot 9 none of the bots work rn I think) https://discord.gg/nRHAhMDr (save is the drive) https://drive.google.com/drive/folders/1m2SVrI6UKFJEKDKFFS1-GzY5B_L2uO0Z?usp=drive_link Hope this helps (Go to \user\savedata\1\CUSA02046 and replace the SAVEDATA00 with the one I gave you) if you don't understand what the guy is saying in the video just add me on Discord and I'll help @callemzanos)
> > > > > > How are yall able to get yalls to load and play? Mines just opens the gamemode and then crashes on the loading screen?
> > > > > 
> > > > > 
> > > > > It didnt worked :0 still tells me to create a new save
> > > > 
> > > > 
> > > > DId you delete your other save?
> > > 
> > > 
> > > I'll make a video and send it to you once I settle down
> > 
> > 
> > Yes I deleted my old save, also trying just overwriting, please it will help many people who are also trying to get the game to function if you share a video of your process, are you using the nightly build? you can get into king of kaiju mode with version v5.0
> 
> https://youtu.be/Vl_dX2lUG7s and yeah I'm going to switch to 5.0 and see if it works (at the end of the video you can see my problem

Video is private so I cant watch it :(

**Comment by Zanosfr** [comment]
> > > > > > > Here is the save file. Got it from here https://www.thetechgame.com/Downloads/id=234516/eu-godzilla-platinum-game-save-cusa02058.html and just decrypted it. if you wanna know how to decrypt your files look at this video https://www.youtube.com/watch?v=UUPi_jHerWI Here is the discord as well (when you're in the discord use bot 9 none of the bots work rn I think) https://discord.gg/nRHAhMDr (save is the drive) https://drive.google.com/drive/folders/1m2SVrI6UKFJEKDKFFS1-GzY5B_L2uO0Z?usp=drive_link Hope this helps (Go to \user\savedata\1\CUSA02046 and replace the SAVEDATA00 with the one I gave you) if you don't understand what the guy is saying in the video just add me on Discord and I'll help @callemzanos)
> > > > > > > How are yall able to get yalls to load and play? Mines just opens the gamemode and then crashes on the loading screen?
> > > > > > 
> > > > > > 
> > > > > > It didnt worked :0 still tells me to create a new save
> > > > > 
> > > > > 
> > > > > DId you delete your other save?
> > > > 
> > > > 
> > > > I'll make a video and send it to you once I settle down
> > > 
> > > 
> > > Yes I deleted my old save, also trying just overwriting, please it will help many people who are also trying to get the game to function if you share a video of your process, are you using the nightly build? you can get into king of kaiju mode with version v5.0
> > 
> > 
> > https://youtu.be/Vl_dX2lUG7s and yeah I'm going to switch to 5.0 and see if it works (at the end of the video you can see my problem
> 
> Video is private so I cant watch it :(, maybe you can change it to "unlisted"

it doesn't work anymore I've tried to make another video to show how but it just isn't working. i deleted everything until further notice. But if it works I'll let you know

**Comment by Zanosfr** [comment]
> > > > > > > Here is the save file. Got it from here https://www.thetechgame.com/Downloads/id=234516/eu-godzilla-platinum-game-save-cusa02058.html and just decrypted it. if you wanna know how to decrypt your files look at this video https://www.youtube.com/watch?v=UUPi_jHerWI Here is the discord as well (when you're in the discord use bot 9 none of the bots work rn I think) https://discord.gg/nRHAhMDr (save is the drive) https://drive.google.com/drive/folders/1m2SVrI6UKFJEKDKFFS1-GzY5B_L2uO0Z?usp=drive_link Hope this helps (Go to \user\savedata\1\CUSA02046 and replace the SAVEDATA00 with the one I gave you) if you don't understand what the guy is saying in the video just add me on Discord and I'll help @callemzanos)
> > > > > > > How are yall able to get yalls to load and play? Mines just opens the gamemode and then crashes on the loading screen?
> > > > > > 
> > > > > > 
> > > > > > It didnt worked :0 still tells me to create a new save
> > > > > 
> > > > > 
> > > > > DId you delete your other save?
> > > > 
> > > > 
> > > > I'll make a video and send it to you once I settle down
> > > 
> > > 
> > > Yes I deleted my old save, also trying just overwriting, please it will help many people who are also trying to get the game to function if you share a video of your process, are you using the nightly build? you can get into king of kaiju mode with version v5.0
> > 
> > 
> > https://youtu.be/Vl_dX2lUG7s and yeah I'm going to switch to 5.0 and see if it works (at the end of the video you can see my problem
> 
> Video is private so I cant watch it :(, maybe you can change it to "unlisted"

Done...Let me know if it works or not. but I've deleted everything intill further notice. so I'll probably play the ps3 version. cause it isn't working for me

**Comment by jasuso2** [comment]
> > > > > > > > Here is the save file. Got it from here https://www.thetechgame.com/Downloads/id=234516/eu-godzilla-platinum-game-save-cusa02058.html and just decrypted it. if you wanna know how to decrypt your files look at this video https://www.youtube.com/watch?v=UUPi_jHerWI Here is the discord as well (when you're in the discord use bot 9 none of the bots work rn I think) https://discord.gg/nRHAhMDr (save is the drive) https://drive.google.com/drive/folders/1m2SVrI6UKFJEKDKFFS1-GzY5B_L2uO0Z?usp=drive_link Hope this helps (Go to \user\savedata\1\CUSA02046 and replace the SAVEDATA00 with the one I gave you) if you don't understand what the guy is saying in the video just add me on Discord and I'll help @callemzanos)
> > > > > > > > How are yall able to get yalls to load and play? Mines just opens the gamemode and then crashes on the loading screen?
> > > > > > > 
> > > > > > > 
> > > > > > > It didnt worked :0 still tells me to create a new save
> > > > > > 
> > > > > > 
> > > > > > DId you delete your other save?
> > > > > 
> > > > > 
> > > > > I'll make a video and send it to you once I settle down
> > > > 
> > > > 
> > > > Yes I deleted my old save, also trying just overwriting, please it will help many people who are also trying to get the game to function if you share a video of your process, are you using the nightly build? you can get into king of kaiju mode with version v5.0
> > > 
> > > 
> > > https://youtu.be/Vl_dX2lUG7s and yeah I'm going to switch to 5.0 and see if it works (at the end of the video you can see my problem
> > 
> > 
> > Video is private so I cant watch it :(, maybe you can change it to "unlisted"
> 
> Done...Let me know if it works or not. but I've deleted everything intill further notice. so I'll probably play the ps3 version. cause it isn't working for me

I didnt worked, It tells me to create another save file, I dont understand what is wrong

**Comment by TheIronWolfx119** [comment]
> > > > > > > > > Here is the save file. Got it from here https://www.thetechgame.com/Downloads/id=234516/eu-godzilla-platinum-game-save-cusa02058.html and just decrypted it. if you wanna know how to decrypt your files look at this video https://www.youtube.com/watch?v=UUPi_jHerWI Here is the discord as well (when you're in the discord use bot 9 none of the bots work rn I think) https://discord.gg/nRHAhMDr (save is the drive) https://drive.google.com/drive/folders/1m2SVrI6UKFJEKDKFFS1-GzY5B_L2uO0Z?usp=drive_link Hope this helps (Go to \user\savedata\1\CUSA02046 and replace the SAVEDATA00 with the one I gave you) if you don't understand what the guy is saying in the video just add me on Discord and I'll help @callemzanos)
> > > > > > > > > How are yall able to get yalls to load and play? Mines just opens the gamemode and then crashes on the loading screen?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It didnt worked :0 still tells me to create a new save
> > > > > > > 
> > > > > > > 
> > > > > > > DId you delete your other save?
> > > > > > 
> > > > > > 
> > > > > > I'll make a video and send it to you once I settle down
> > > > > 
> > > > > 
> > > > > Yes I deleted my old save, also trying just overwriting, please it will help many people who are also trying to get the game to function if you share a video of your process, are you using the nightly build? you can get into king of kaiju mode with version v5.0
> > > > 
> > > > 
> > > > https://youtu.be/Vl_dX2lUG7s and yeah I'm going to switch to 5.0 and see if it works (at the end of the video you can see my problem
> > > 
> > > 
> > > Video is private so I cant watch it :(, maybe you can change it to "unlisted"
> > 
> > 
> > Done...Let me know if it works or not. but I've deleted everything intill further notice. so I'll probably play the ps3 version. cause it isn't working for me
> 
> I didnt worked, It tells me to create another save file, I dont understand what is wrong

Same. I have tried multiple save files, resigning, re regioning everything. Always tells me to make a new save.

Now the version of the game I have is 1.00 and it looks like the guy we replying to on his post is 1.01

Maybe that might be the issue in my case as all the save files may be for a more updated version of the game than I have. only thing I can think of but I couldn't find a newer version of the game in my searching as of now. Ill update here if something changes on my end.

**Comment by Zanosfr** [comment]
> > > > > > > > > > Here is the save file. Got it from here https://www.thetechgame.com/Downloads/id=234516/eu-godzilla-platinum-game-save-cusa02058.html and just decrypted it. if you wanna know how to decrypt your files look at this video https://www.youtube.com/watch?v=UUPi_jHerWI Here is the discord as well (when you're in the discord use bot 9 none of the bots work rn I think) https://discord.gg/nRHAhMDr (save is the drive) https://drive.google.com/drive/folders/1m2SVrI6UKFJEKDKFFS1-GzY5B_L2uO0Z?usp=drive_link Hope this helps (Go to \user\savedata\1\CUSA02046 and replace the SAVEDATA00 with the one I gave you) if you don't understand what the guy is saying in the video just add me on Discord and I'll help @callemzanos)
> > > > > > > > > > How are yall able to get yalls to load and play? Mines just opens the gamemode and then crashes on the loading screen?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > It didnt worked :0 still tells me to create a new save
> > > > > > > > 
> > > > > > > > 
> > > > > > > > DId you delete your other save?
> > > > > > > 
> > > > > > > 
> > > > > > > I'll make a video and send it to you once I settle down
> > > > > > 
> > > > > > 
> > > > > > Yes I deleted my old save, also trying just overwriting, please it will help many people who are also trying to get the game to function if you share a video of your process, are you using the nightly build? you can get into king of kaiju mode with version v5.0
> > > > > 
> > > > > 
> > > > > https://youtu.be/Vl_dX2lUG7s and yeah I'm going to switch to 5.0 and see if it works (at the end of the video you can see my problem
> > > > 
> > > > 
> > > > Video is private so I cant watch it :(, maybe you can change it to "unlisted"
> > > 
> > > 
> > > Done...Let me know if it works or not. but I've deleted everything intill further notice. so I'll probably play the ps3 version. cause it isn't working for me
> > 
> > 
> > I didnt worked, It tells me to create another save file, I dont understand what is wrong
> 
> Same. I have tried multiple save files, resigning, re regioning everything. Always tells me to make a new save.
> 
> Now the version of the game I have is 1.00 and it looks like the guy we replying to on his post is 1.01
> 
> Maybe that might be the issue in my case as all the save files may be for a more updated version of the game than I have. only thing I can think of but I couldn't find a newer version of the game in my searching as of now. Ill update here if something changes on my end.

https://archive.org/details/Godzilla_CollectionArchive-LivBs this is where I got my files. the 1.01 patch is there with the game if you scroll and download the USA ps4 version.

**Comment by Zanosfr** [comment]
Good news! I was able to find the sys module files online, so I can finally play! Here is the link in case you don't have them: https://drive.google.com/file/d/1wdxqeHRYGFCozhSM96niXgkzkLlCdpDY/view. However, I can't see the text when I open all the game modes. I think there might be something else I need to include for the libraries. Other than that, I’ve fixed my issue!

**Comment by MrDorkian** [comment]
> Good news! I was able to find the sys module files online, so I can finally play! Here is the link in case you don't have them: https://drive.google.com/file/d/1wdxqeHRYGFCozhSM96niXgkzkLlCdpDY/view. However, I can't see the text when I open all the game modes. I think there might be something else I need to include for the libraries. Other than that, I’ve fixed my issue!

Quick question, where do you put the modules?

**Comment by Zanosfr** [comment]
> > Good news! I was able to find the sys module files online, so I can finally play! Here is the link in case you don't have them: https://drive.google.com/file/d/1wdxqeHRYGFCozhSM96niXgkzkLlCdpDY/view. However, I can't see the text when I open all the game modes. I think there might be something else I need to include for the libraries. Other than that, I’ve fixed my issue!
> 
> Quick question, where do you put the modules?

go to user and you will see sys_modules

**Comment by MrDorkian** [comment]
> > > Good news! I was able to find the sys module files online, so I can finally play! Here is the link in case you don't have them: https://drive.google.com/file/d/1wdxqeHRYGFCozhSM96niXgkzkLlCdpDY/view. However, I can't see the text when I open all the game modes. I think there might be something else I need to include for the libraries. Other than that, I’ve fixed my issue!
> > 
> > 
> > Quick question, where do you put the modules?
> 
> go to user and you will see sys_modules

Ah, thanks

**Comment by jasuso2** [comment]
It finally worked! I downloaded that USA Rom and applied the 1.1 patch, saves work now, King of Kaiju is playable with all monsters, not a single crash, pristine performance, finally I can play this game without having to waste 300+ dollars for it

**Comment by Zanosfr** [comment]
> It finally worked! I downloaded that USA Rom and applied the 1.1 patch, saves work now, King of Kaiju is playable with all monsters, not a single crash, pristine performance, finally I can play this game without having to waste 300+ dollars for it

I know right!? lol  It was nice working this out with you guys. Have fun playing!

**Comment by Zanosfr** [comment]
By the way do you just wait until your unsoft locked or do you have to do something in order to get rid of it

**Comment by TheIronWolfx119** [comment]
> > It finally worked! I downloaded that USA Rom and applied the 1.1 patch, saves work now, King of Kaiju is playable with all monsters, not a single crash, pristine performance, finally I can play this game without having to waste 300+ dollars for it
> 
> I know right!? lol It was nice working this out with you guys. Have fun playing!
Yup this solved my issue as well. Everything is playable other than the tutorial. OP audio is missing, and some text is missing but easily playable.

Reading this I wish I had thought to tell you to get sysm modules as that I did have already, my bad. We all were missing like one thing just different from each one of us.

But this is all here now for any other G fans to read and get their hands on. Great work!

**Comment by Borsh275** [comment]
hey im writing this a little late but ive done everthing told in this chat but my game continues to crash still

**Comment by yinjbc123** [comment]
Just a quick question. Am i meant to patch the game from the files here ? https://archive.org/details/Godzilla_CollectionArchive-LivBs
