### ISSUE TITLE
CUSA06840 - Stardew Valley

### ISSUE THREAD

**Issue by SSoroushS** [shadps4-emu/shadps4-game-compatibility#1583]
### Game Name

Stardew Valley

### Game code

CUSA06840

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.1 WIP

### Current status

Menus

### Operating System

Windows

### Error

[Lib.Ngs2] <Error> ngs2.cpp:sceNgs2SystemRender:229: (STUBBED) called
[Lib.Ngs2] <Error> ngs2.cpp:sceNgs2SystemRender:229: (STUBBED) called
[Lib.Ngs2] <Error> ngs2.cpp:sceNgs2SystemRender:229: (STUBBED) called

### Description

the game boots normally and I can completely navigate through the menu, however, due to the lack of keyboard support and being unable to write a username I cannot create a save file and play the game and thus the game is stuck in the menu. I would also like to mention that in the previous versions I couldn't at all boot into the game so this is a huge improvement

### Screenshots

![Screenshot 2024-12-28 011733](https://github.com/user-attachments/assets/0468233a-24e3-4982-9021-c127aa416bbc)
![Screenshot 2024-12-28 011752](https://github.com/user-attachments/assets/4f74328b-76d8-4325-aa4f-e3a38deff89d)
![Screenshot 2024-12-28 011812](https://github.com/user-attachments/assets/be924e3d-4e75-4dd6-8554-731cd23589c6)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18264445/shad_log.txt)

**Comment by Xphalnos** [comment]
Duplicated from https://github.com/shadps4-emu/shadps4-game-compatibility/issues/564.
Please update it by commenting. Thanks
