### ISSUE TITLE
CUSA07988 - Bunny Must Die! Chelsea and the 7devils.

### ISSUE THREAD

**Issue by omegakuno** [shadps4-emu/shadps4-game-compatibility#1589]
### Game Name

Bunny Must Die! Chelsea and the 7devils.

### Game code

CUSA07988

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.1 WIP

### Current status

Playable

### Operating System

Windows

### Error

Input - Inputlag sometimes.
Using Xbox Series Controller

### Description

Game Runs fine, sometimes input lag happens.
Image/Video - Perfect
Sound - Perfect and Sync
Input - Sometimes input Lag, Sometimes Double press

### Screenshots

![Captura de tela 2024-12-28 010117](https://github.com/user-attachments/assets/4ba5bd49-c7a1-4e1f-bf4b-fad45e62bda9)
![Captura de tela 2024-12-28 010132](https://github.com/user-attachments/assets/8931d30e-aadc-4368-b9e4-789169d7d1db)
![Captura de tela 2024-12-28 005856](https://github.com/user-attachments/assets/6d773b2c-8470-4d3d-9b81-c6d826520c4c)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18264897/shad_log.txt)

**Comment by Xphalnos** [comment]
Work in progress versions are not accepted! Please reopen a report with version 0.5.0. Thank you
