### ISSUE TITLE
CUSA24159 - Ghosts 'n Goblins Resurrection

### ISSUE THREAD

**Issue by Francyemu226** [shadps4-emu/shadps4-game-compatibility#1629]
### Game Name

Ghosts 'n Goblins Resurrection

### Game code

CUSA24159

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.1 WIP

### Current status

Nothing

### Operating System

Windows

### Error

[Kernel.Vmm] <Warning> memory.cpp:sceKernelGetDirectMemorySize:22: called
[Debug] <Critical> memory.cpp:operator():119: Assertion Failed!
Unable to find free direct memory area: size = 0x20000

### Description

Crashes instantly

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18269913/shad_log.txt)

**Comment by Xphalnos** [comment]
WIP versions are not allowed! Please reopen a report on a stable version! (0.5.0)
