### ISSUE TITLE
CUSA28037 - Chernobylite

### ISSUE THREAD

**Issue by lastclass74** [shadps4-emu/shadps4-game-compatibility#1631]
### Game Name

Chernobylite

### Game code

CUSA28037

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.1 WIP

### Current status

Nothing

### Operating System

Windows

### Error

crash emulator

### Description

nothing

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18270002/shad_log.txt)

**Comment by Xphalnos** [comment]
WIP versions are not allowed! Please reopen a report on a stable version! (0.5.0)
