### ISSUE TITLE
CUSA10592 - Heroine Anthem Zero Episode 1

### ISSUE THREAD

**Issue by Francyemu226** [shadps4-emu/shadps4-game-compatibility#1632]
### Game Name

Heroine Anthem Zero Episode 1

### Game code

CUSA10592

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.1 WIP

### Current status

Ingame

### Operating System

Windows

### Error

this error repeats... but the game does not crash

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceMouseRead (nid: x8qnXqh-tiM) called, returning zero to 0x900f05006
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceMouseRead (nid: x8qnXqh-tiM) called, returning zero to 0x900f05006
[Lib.Pad] <Info> pad.cpp:scePadSetLightBar:464: scePadSetLightBar called handle = -1 rgb = 255 255 0

### Description

the game is playable i done first e second level unlock archivments

in graphics some imperfections every now and then

### Screenshots

<img width="960" alt="Heroine Anthem Zero Episode 1" src="https://github.com/user-attachments/assets/8f8ef622-c752-489a-ae64-8fac9bb04ac2" />
<img width="961" alt="Heroine Anthem Zero Episode 1_2" src="https://github.com/user-attachments/assets/24f91edf-918b-47df-b7f9-545fd2014f62" />
<img width="959" alt="Heroine Anthem Zero Episode 1_3" src="https://github.com/user-attachments/assets/0f2d6c66-6cd6-43ab-867a-4a0102c161b1" />

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18269982/shad_log.txt)

**Comment by Xphalnos** [comment]
WIP versions are not allowed! Please reopen a report on a stable version! (0.5.0)
