### ISSUE TITLE
CUSA04622 - ULTIMATE MARVEL VS. CAPCOM 3

### ISSUE THREAD

**Issue by DLADAnaconda** [shadps4-emu/shadps4-game-compatibility#1647]
### Game Name

ULTIMATE MARVEL VS. CAPCOM 3

### Game code

CUSA04622

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Ingame

### Operating System

Windows

### Error

Tested the game with sys modules for firmware 11, is ps4 pro disabled, no game updates, and the game botts and plays fine. There is sound. 
The only issues with the sound that is obvious to me is that the characters don't say their lines when you get in a matchm nor when you win a match, there is no sound, but other than that plays fine.
With ps4 pro enabled, you cannot get to the game cinematic intro because the game crashes.

Tested the game without sys modules, plays a few intro logos then it crashes + no sound.

### Description

Tested the game with sys modules for firmware 11, is ps4 pro disabled, no game updates, and the game botts and plays fine. There is sound. 
The only issues with the sound that is obvious to me is that the characters don't say their lines when you get in a matchm nor when you win a match, there is no sound, but other than that plays fine.
With ps4 pro enabled, you cannot get to the game cinematic intro because the game crashes.

Tested the game without sys modules, plays a few intro logos then it crashes + no sound.

### Screenshots

![shadPS4_xrorrKzMQB](https://github.com/user-attachments/assets/b9eabdff-6ce3-4823-8512-bd97863e86f7)
![shadPS4_bWb0IW41la](https://github.com/user-attachments/assets/438e3b58-cb21-4b19-beeb-449afa70670f)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18270878/shad_log.txt)

**Comment by Xphalnos** [comment]
Duplicated of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/151.
