### ISSUE TITLE
CUSA00743 - Peggle 2

### ISSUE THREAD

**Issue by DLADAnaconda** [shadps4-emu/shadps4-game-compatibility#1655]
### Game Name

Peggle 2

### Game code

CUSA00743

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Nothing

### Operating System

Windows

### Error

Tested with sys modules for firmware 11, ps4 pro on/off, with/without dlcs, same result every time = game tends to boot then in the very first few seconds after the game boots and you hear about 3 seconds of audio it freezes.

### Description

Tested with sys modules for firmware 11, ps4 pro on/off, with/without dlcs, same result every time = game tends to boot then in the very first few seconds after the game boots and you hear about 3 seconds of audio it freezes.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18271247/shad_log.txt)

**Comment by Xphalnos** [comment]
Duplicated of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/494. Please update it by comment.

**Comment by DLADAnaconda** [comment]
> Duplicated of #494. Please update it by comment.

I didn't find the thread by searching and also the compatibility in my Shad ps4 emu is displaying info for other platforms, it doesn't detect my os every time, so that's why I start new threads sometimes.
