### ISSUE TITLE
CUSA00093 - DRIVECLUB

### ISSUE THREAD

**Issue by datothercesar** [shadps4-emu/shadps4-game-compatibility#1662]
### Game Name

DRIVECLUB

### Game code

CUSA00093

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.50

### Current status

Nothing

### Operating System

Windows

### Error

Blank screen, program gets stuck in a loop
[Lib.Usbd] <Error> usbd.cpp:sceUsbdInit:223: (STUBBED)called
[Lib.Usbd] <Error> usbd.cpp:sceUsbdHandleEventsTimeout:218: (STUBBED)called

### Description

Nothing

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18273054/shad_log.txt)

**Comment by Xphalnos** [comment]
Duplicated of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/129. Please update by comment.
