### ISSUE TITLE
CUSA03263 - Mount & Blade: Warband

### ISSUE THREAD

**Issue by AhayriSG** [shadps4-emu/shadps4-game-compatibility#1672]
### Game Name

Mount & Blade: Warband

### Game code

CUSA03263

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

v0.5.1

### Current status

Playable

### Operating System

Windows

### Error

"No errors occur except that my character automatically runs in random directions when I release the left analog stick.

### Description

Plays fine without any game breaking bugs or graphical issues

### Screenshots

![image](https://github.com/user-attachments/assets/d0563cc2-c28c-4b01-9a42-2de9c1284eb8)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18274303/shad_log.txt)

**Comment by Hermiten** [comment]
Nice to see this game playable but we only accept test on éajor release like 0.5.0 Thanks you
