### ISSUE TITLE
bloodborne doesn't run after update.

### ISSUE THREAD

**Issue by diokane99** [shadps4-emu/shadps4-game-compatibility#1693]
### Game Name

Bloodborne

### Game code

CUSA03173

### Game version

01.09

### Used emulator's version (only released versions are acceptable)

0.5.1.

### Current status

Ingame

### Operating System

Windows

### Error

.

### Description

after the last update bloodborne not running at all, always works till now.

### Screenshots

![shadPS4 v0 5 1 WIP mainBB 30e5cad 30_12_2024 20_57_26](https://github.com/user-attachments/assets/bb154a36-5fac-437a-896c-37c2b47639ed)

### Log File

..

**Comment by C4ndyF1sh** [comment]
1. WIP versions are not allowed to be submitted here 2. Bloodborne was reported multiple times 3. try a second time, currently there is a bug that makes game crash on the first boot but on the 2nd and later it should work fine
