### ISSUE TITLE
CUSA00223 - inFAMOUS Second Son™

### ISSUE THREAD

**Issue by aboofS** [shadps4-emu/shadps4-game-compatibility#1713]
### Game Name

inFAMOUS Second Son™

### Game code

CUSA00223

### Game version

01.07

### Used emulator's version (only released versions are acceptable)

0.5.1 WIP

### Current status

Boots

### Operating System

Windows

### Error

Error for Update 0.5.1  Nightly Release :[Debug] <Critical> liverpool_to_vk.h:PromoteFormatToDepth:79: Unreachable code!
Error for Update 0.5.0 Normal Release :[Debug] <Critical> liverpool_to_vk.h:PromoteFormatToDepth:88: Unreachable code!

### Description

On both the normal and nightly releases the game boots and loads the splash screen, after that it only shows a black screen and then crashes

### Screenshots

![sc1](https://github.com/user-attachments/assets/d69a1210-c591-47a8-8bca-4400a3346d5a)
![sc2](https://github.com/user-attachments/assets/c1dad189-5656-463a-92ea-8107647127de)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18278076/shad_log.txt)
[Normal release shad_log.txt](https://github.com/user-attachments/files/18278091/Normal.release.shad_log.txt)

**Comment by Xphalnos** [comment]
Duplicated of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/3. Only stable releases (0.5.0) are allowed! You can update https://github.com/shadps4-emu/shadps4-game-compatibility/issues/3 by a comment.
