### ISSUE TITLE
CUSA10249 - The Last of Us™ Part II

### ISSUE THREAD

**Issue by marcosmurakami** [shadps4-emu/shadps4-game-compatibility#1717]
### Game Name

The Last of Us™ Part II

### Game code

CUSA10249

### Game version

01.07

### Used emulator's version (only released versions are acceptable)

0.5.1 WIP

### Current status

Nothing

### Operating System

Windows

### Error

None.

### Description

No error message, the emulator crashes. 

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18278270/shad_log.txt)

**Comment by DanyPrianta** [comment]
stable version only

**Comment by Xphalnos** [comment]
Duplicated of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1065. Only stable releases (0.5.0) are allowed! You can update https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1065 by a comment.
