### ISSUE TITLE
CUSA18557 Zaccaria Pinball 

### ISSUE THREAD

**Issue by AussiePlick** [shadps4-emu/shadps4-game-compatibility#1726]
### Game Name

Zaccaria Pinball

### Game code

CUSA18557

### Game version

1.00

### Used emulator's version (only released versions are acceptable)

0.5.0

### Current status

Menus

### Operating System

Windows

### Error

Perfect sound and video to menu.
Cant go beyond first Menu item.

### Description

Perfect sound and video to menu.

### Screenshots

![Zaccaria Pinball](https://github.com/user-attachments/assets/f41e7245-0c50-49ae-b383-864680cffdfc)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18279852/shad_log.txt)

**Comment by ArbestRi02** [comment]
Duplicate of #1707

**Comment by Xphalnos** [comment]
Duplicated of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1707.
