### ISSUE TITLE
CUSA04802 - 2Dark

### ISSUE THREAD

**Issue by Zol77** [shadps4-emu/shadps4-game-compatibility#1729]
### Game Name

2Dark

### Game code

CUSA04802

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.5.0

### Current status

Playable

### Operating System

Windows

### Error

[Lib.Ngs2] <Error> ngs2.cpp:sceNgs2SystemRender:229: (STUBBED) called

### Description

the game is playable,but no sound,no music.

### Screenshots

![2d1](https://github.com/user-attachments/assets/29691ce6-28fb-4c5f-a35d-812f83a8ccfa)
![2d2](https://github.com/user-attachments/assets/a25bcc22-210f-468b-aab0-154057b4a573)
![2d3](https://github.com/user-attachments/assets/8f3c83bc-9fbf-4f85-9eaa-27c58037d32b)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/18281022/shad_log.txt)

**Comment by Xphalnos** [comment]
Duplicated of https://github.com/shadps4-emu/shadps4-game-compatibility/issues/855. Please update it by a comment.
