### ISSUE TITLE
CUSA01839 - Ultra Street Fighter IV

### ISSUE THREAD

**Issue by zemzema** [shadps4-emu/shadps4-game-compatibility#174]
### Game Name

Ultra Street Fighter IV

### Game code

CUSA01839

### Game version

01.07

### Used emulator's version (only released versions are acceptable)

0.1.1 WIP

### Current status

Boots

### Error

[Tty] <Info> libkernel.cpp:ps4__write:171: [SceLibc] 0x00000001523c7fd0: 0x00000001526827b2 0x0000000152409fd0
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceKernelPrintBacktraceWithModuleInfo (nid: Wl2o5hOVZdw) called, returning zero to 0x9100268b4
[Debug] <Critical> libkernel.cpp:sceKernelDebugRaiseException:310: Unreachable code!

### Description

After save game warning when I tried to enter the game, emulator crash.

### Screenshots

![image](https://github.com/user-attachments/assets/161c5363-47e6-4dd1-8bbd-e512600c032e)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16325765/shad_log.txt)

**Comment by georgemoralis** [comment]
Only release versions permitted (at current time v0.1.0) . Closing...
