### ISSUE TITLE
CUSA11995 - Marvel's Spider-Man

### ISSUE THREAD

**Issue by zemzema** [shadps4-emu/shadps4-game-compatibility#175]
### Game Name

Marvel's Spider-Man

### Game code

CUSA11995

### Game version

01.05

### Used emulator's version (only released versions are acceptable)

0.1.1 WIP

### Current status

Nothing

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: pthread_attr_setinheritsched (nid: 7ZlAakEf0Qg) called, returning zero to 0x9015cc66b
[Core] <Error> stubs.cpp:CommonStub:42: Stub: pthread_attr_setschedparam (nid: euKRgm0Vn2M) called, returning zero to 0x9015cc67d

### Description

Nothing.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16325783/shad_log.txt)

**Comment by georgemoralis** [comment]
Only release versions permitted (at current time v0.1.0) . Closing...
