### ISSUE TITLE
CUSA10866 - Burnout Paradise Remastered

### ISSUE THREAD

**Issue by huntyboy102** [shadps4-emu/shadps4-game-compatibility#176]
### Game Name

Burnout Paradise Remastered

### Game code

CUSA10866

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.1.1 WIP

### Current status

Nothing

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: _sceKernelSetThreadDtors (nid: rNhWz+lvOMU) called, returning zero to 0x9100006d0
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _sceKernelSetThreadAtexitCount (nid: pB-yGZ2nQ9o) called, returning zero to 0x9100006dc
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _sceKernelSetThreadAtexitReport (nid: WhCc1w3EhSI) called, returning zero to 0x9100006e8
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceKernelGetSanitizerNewReplaceExternal (nid: bnZxYgAFeA0) called, returning zero to 0x9100726e3
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceKernelIsAddressSanitizerEnabled (nid: jh+8XiK4LeE) called, returning zero to 0x9100298aa

### Description

Nothing.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16325827/shad_log.txt)

**Comment by georgemoralis** [comment]
Only release versions permitted (at current time v0.1.0) . Closing...
