### ISSUE TITLE
CUSA00897 - inFAMOUS™ First Light

### ISSUE THREAD

**Issue by Digote** [shadps4-emu/shadps4-game-compatibility#188]
### Game Name

inFAMOUS™ First Light

### Game code

CUSA00897

### Game version

v1.0

### Used emulator's version (only released versions are acceptable)

v0.1.0

### Current status

Nothing

### Error

[Lib.Pad] <Error> pad.cpp:scePadInit:177: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetInit:761: (DUMMY) called
[Lib.NetCtl] <Error> netctl.cpp:sceNetCtlInit:242: (STUBBED) called
[Lib.NetCtl] <Error> netctl.cpp:sceNetCtlGetState:217: (STUBBED) called

### Description

The emulator gets stuck with these last errors.

### Log File

[shad_log.zip](https://github.com/user-attachments/files/16419273/shad_log.zip)

**Comment by georgemoralis** [comment]
duplicate
