### ISSUE TITLE
CUSA04892 - Mighty Morphin Power Rangers: Mega Battle

### ISSUE THREAD

**Issue by MaxPie93** [shadps4-emu/shadps4-game-compatibility#215]
### Game Name

Mighty Morphin Power Rangers: Mega Battle

### Game code

CUSA04892

### Game version

1.00

### Used emulator's version (only released versions are acceptable)

0.1.1

### Current status

Boots

### Error

Critical error

### Description

Boots, but crashed

### Screenshots

![изображение_2024-07-31_150039255](https://github.com/user-attachments/assets/c9344cc0-6a4b-4811-928c-fbb96e48e6fe)

**Comment by georgemoralis** [comment]
Sorry only release version (at present 0.1.0) is permitted for compatibility reports

**Comment by Fatchk** [comment]
![image](https://github.com/user-attachments/assets/f539d0bf-7f0f-49fa-a49a-95fc5cbaa7ff)

Boots but doesn't go past this screen and all the text is not showing right.
