### ISSUE TITLE
Mahjong (GPU Radeon)

### ISSUE THREAD

**Issue by Haroldo777** [shadps4-emu/shadps4-game-compatibility#217]
### Game Name

Mahjong

### Game code

CUSA05079

### Game version

1.0

### Used emulator's version (only released versions are acceptable)

0.1.1 WIP

### Current status

Nothing

### Error

[Novo Documento de Texto.txt](https://github.com/user-attachments/files/16460154/Novo.Documento.de.Texto.txt)

### Description

emulator crashes

**Comment by Digote** [comment]
This is the compatibility tracker for PlayStation 4 games on shadPS4.

Rules:

**Only publish results from major [shadPS4 releases](https://github.com/shadps4-emu/shadPS4/releases) (e.g. 0.1.0).**
