### ISSUE TITLE
Call of Duty: Black Ops 6

### ISSUE THREAD

**Issue by 1226608** [shadps4-emu/shadps4-game-compatibility#242]
### Game Name

Call of Duty: Black Ops 6

### Game code

CUSA23827

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

01.00

### Current status

Playable

### Error

[Lib.MsgDlg] <Error> msgdialog.cpp:sce Msg Dialog Update Status:60: (STUBBED) called

### Description

[Lib.MsgDlg] <Error> msgdialog.cpp:sce Msg Dialog Update Status:60: (STUBBED) called

**Comment by raphaelthegreat** [comment]
Testing leaked games is not allowed
