### ISSUE TITLE
CUSA01648 - Final Fantasy XV: EPISODE DUSCAE

### ISSUE THREAD

**Issue by lemmeusethefuckingps4emu** [shadps4-emu/shadps4-game-compatibility#260]
### Game Name

Final Fantasy XV: EPISODE DUSCAE

### Game code

CUSA01648

### Game version

v1.2

### Used emulator's version (only released versions are acceptable)

v0.1.1

### Current status

Nothing

### Error

// Unresolved modules
[Core.Linker] <Error> linker.cpp:Resolve:240: Not Resolved module_stop
[Core.Linker] <Error> linker.cpp:Resolve:240: Not Resolved module_start
// Unsupported thread priority attribute for event flag
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCreate:1031: thread create name = BlackFileSystem
[Kernel.Event] <Info> event_flag.cpp:sceKernelCreateEventFlag:15: called name = EbonyEvent attr = 0x12 initPattern = 0x0
[Kernel.Event] <Error> event_flag.cpp:sceKernelCreateEventFlag:58: ThreadPriority attr is not supported!
// Forever:
[Kernel.Event] <Info> event_flag.cpp:sceKernelWaitEventFlag:148: called bitPattern = 0x1 waitMode = 0x12
// Unsupported thread schedule policy
[Kernel.Pthread] <Error> thread_management.cpp:scePthreadAttrSetschedpolicy:280: policy=1 not supported by winpthreads
// Tile format missing
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:392: Unsupported tiled image: B8G8R8A8Srgb (Display_MacroTiled)

### Description

Black screen. no sounds no menus nothing from the get go.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16563788/shad_log.txt)

**Comment by georgemoralis** [comment]
compatibility list is only for released versions (atm only 0.1.0)
