### ISSUE TITLE
(CUSA13795) Crash Team Racing Nitro-Fueled

### ISSUE THREAD

**Issue by DiverseBloom780** [shadps4-emu/shadps4-game-compatibility#269]
### Game Name

Crash Team Racing Nitro-Fueled

### Game code

CUSA13795

### Game version

V1.0

### Used emulator's version (only released versions are acceptable)

v0.1.0

### Current status

Nothing

### Error

[Kernel.Pthread] <Info> thread_management.cpp:posix_pthread_cond_broadcast:787: posix posix_pthread_cond_broadcast redirect to scePthreadCondBroadcast
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = ORBIS_SYSMODULE_NP_COMMERCE
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = ORBIS_SYSMODULE_NP_COMMERCE
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/dlog/events.dlog flags = 0x0 mode = 511
[Kernel.Fs] <Info> file_system.cpp:sceKernelFStat:319: (PARTIAL) fd = 18
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCondWait:1066: scePthreadCondWait, result=0

### Description

it ran and then paused and gave some application error, resumed running and then crashed, no sound or graphics

### Screenshots

![Desktop Screenshot 2024 08 09 - 20 59 10 93](https://github.com/user-attachments/assets/55a7e114-d2d5-4505-807e-d83bead5a8ac)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16568148/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicated
