### ISSUE TITLE
(CUSA19345) Sonic Colors: Ultimate

### ISSUE THREAD

**Issue by DiverseBloom780** [shadps4-emu/shadps4-game-compatibility#278]
### Game Name

Sonic Colors: Ultimate

### Game code

CUSA19345

### Game version

V1.0

### Used emulator's version (only released versions are acceptable)

v0.1.0

### Current status

Nothing

### Error

Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexDestroy:452: name=SceLibc_FileFD:0x7FFF800E, result=0
[Lib.GnmDriver] <Error> gnmdriver.cpp:sceGnmGetGpuCoreClockFrequency:916: (STUBBED) called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitAndFlipCommandBuffers:1885: called [buf = 0]
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:1909: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitDone:1989: called
[Lib.SystemService] <Info> systemservice.cpp:sceSystemServiceHideSplashScreen:1797: called
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceImeUpdate (nid: -4GCfYdNF1s) called, returning zero to 0x900007de5
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:1909: called
[Core] <Error> stubs.cpp:CommonStub:42: Stub: scePthreadGetthreadid (nid: EI-5-jlq2dE) called, returning zero to 0x9008dd719

### Description

opens and runs, there was some popping sounds going on but no graphics

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16570812/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicated

**Comment by DiverseBloom780** [comment]
> duplicated

sorry about that, had no idea that has already been posted here in the Compatibility
