### ISSUE TITLE
CUSA02046 - Godzilla

### ISSUE THREAD

**Issue by carlosgamer23** [shadps4-emu/shadps4-game-compatibility#329]
### Game Name

Godzilla VS (Also known as Godzilla 2014)

### Game code

CUSA02046

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.1.0

### Current status

Nothing

### Error

Godzilla 2014/VS won't start and closes the emulator. I think the log explanation is better than something I can write here...

### Description

Godzilla 2014/VS won't start and closes the emulator. I think the log explanation is better than something I can write here...

### Log File

[shad_log_055656.txt](https://github.com/user-attachments/files/16632647/shad_log_055656.txt)

**Comment by carlosgamer23** [comment]
It with the update installed has a different numbering: US Godzilla Patch 01.01: CUSA02058

**Comment by georgemoralis** [comment]
that can't happend , cusa numbering should be equal

**Comment by carlosgamer23** [comment]
> that can't happend , cusa numbering should be equal

I don't know if it changes when you install the game update, so I left the update number as well, that's it.
