### ISSUE TITLE
CUSA00365 Dynasty Warriors 8 Xtreme Legends

### ISSUE THREAD

**Issue by chronicer** [shadps4-emu/shadps4-game-compatibility#334]
### Game Name

Dynasty Warriors 8 Xtreme Legends

### Game code

CUSA00365 

### Game version

v. 0.1

### Used emulator's version (only released versions are acceptable)

v0.21

### Current status

Playable

### Error

Black screen with

[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format D16UnormS8Uint is not supported and no suitable alternative is supported.
[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format A2R10G10B10SnormPack32 is not supported and no suitable alternative is supported.
[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format R8G8B8A8Uscaled is not supported and no suitable alternative is supported.
[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format R16G16Sscaled is not supported and no suitable alternative is supported.
[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format R32G32B32Sfloat is not supported and no suitable alternative is supported.
[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format R32G32B32Uint is not supported and no suitable alternative is supported.
[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format R16G16B16A16Sscaled is not supported and no suitable alternative is supported.

### Description

Black screen with

[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format D16UnormS8Uint is not supported and no suitable alternative is supported.
[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format A2R10G10B10SnormPack32 is not supported and no suitable alternative is supported.
[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format R8G8B8A8Uscaled is not supported and no suitable alternative is supported.
[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format R16G16Sscaled is not supported and no suitable alternative is supported.
[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format R32G32B32Sfloat is not supported and no suitable alternative is supported.
[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format R32G32B32Uint is not supported and no suitable alternative is supported.
[Render.Vulkan] <Error> vk_instance.cpp:Instance:129: Format R16G16B16A16Sscaled is not supported and no suitable alternative is supported.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16641852/shad_log.txt)

**Comment by chronicer** [comment]
[shad_log.txt](https://github.com/user-attachments/files/16641864/shad_log.txt)

New log, sorry for my fault

**Comment by georgemoralis** [comment]
seems you used 0.2.1 WIP only release versions are acceptable in compatibility list , closing
