### ISSUE TITLE
UFC4 does not start

### ISSUE THREAD

**Issue by Lepexa-cell** [shadps4-emu/shadps4-game-compatibility#347]
### Game Name

UFC 4

### Game code

CUSA 14209

### Game version

28.00

### Used emulator's version (only released versions are acceptable)

0.2.0

### Current status

Playable

### Error

![Снимок экрана 2024-08-19 204700](https://github.com/user-attachments/assets/851cc228-7e65-45e1-bf70-6040e3ce3788)
![Снимок экрана 2024-08-19 205007](https://github.com/user-attachments/assets/dc762f2f-7e00-4a39-958f-c01dcee927b7)
![Снимок экрана 2024-08-19 205026](https://github.com/user-attachments/assets/c37e296a-0337-421c-a0d0-3f93e9554c90)

### Description

The game crashes immediately after launch

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16662637/shad_log.txt)

**Comment by georgemoralis** [comment]
no proper report
