### ISSUE TITLE
CUSA03173 - BloodBorne

### ISSUE THREAD

**Issue by Arthurfogo7** [shadps4-emu/shadps4-game-compatibility#365]
### Game Name

BloodBorne

### Game code

CUSA03173

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Menus

### Error

[Debug] <Critical> buffer.cpp:operator():93: Assertion Failed!

### Description

I have no idea why in my case it crashes in the loading screen, after making my character. I see a lot of people managing to get in-game, and I just can't. My cpu is the I5 12400F. 

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16685437/shad_log.txt)

**Comment by ArbestRi02** [comment]
It doesn't go ingame because you're not using 1.09 and the bb-hacks version of shadPS4.

**Comment by georgemoralis** [comment]
duplicate

**Comment by AngryMang0** [comment]
> It doesn't go ingame because you're not using 1.09 and the bb-hacks version of shadPS4.

I'm using 1.09 and have the hack version of shadps4, still can't get over after I "made" my character, often get a couple of purple messages about shaders or just "device memory".
