### ISSUE TITLE
CUSA14209 - UFC 4

### ISSUE THREAD

**Issue by Demons779** [shadps4-emu/shadps4-game-compatibility#373]
### Game Name

UFC 4

### Game code

CUSA14209

### Game version

28.00

### Used emulator's version (only released versions are acceptable)

v0.2.1 WIP

### Current status

Nothing

### Error

Ea Sports UFC 4 the game does not start, the emulator crashes

### Description

Ea Sports UFC 4 the game does not start, the emulator crashes

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16696413/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicated
