### ISSUE TITLE
CUSA10135 — The Witch and the Hundred Knight 2

### ISSUE THREAD

**Issue by Jakiria** [shadps4-emu/shadps4-game-compatibility#390]
### Game Name

The Witch and the Hundred Knight 2

### Game code

CUSA10135

### Game version

1.00

### Used emulator's version (only released versions are acceptable)

0.2.0

### Current status

Nothing

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x9011393d7
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceGetState (nid: -TOuuAQ-buE) called, returning zero to 0x901139414

### Description

The game doesn't start at all. Just black screen while trying to boot and crashing.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16731128/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicate
