### ISSUE TITLE
CUSA27387 - Hades

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#401]
### Game Name

Hades

### Game code

CUSA27387

### Game version

v1.03

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Nothing

### Error

[Lib.SaveDataDialog] <Error> savedatadialog.cpp:sceSaveDataDialogUpdateStatus:57: (STUBBED) called

### Description

Black screen then crashes after a few seconds.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16739628/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions are acceptable
