### ISSUE TITLE
CUSA12916 - Spirit Hunter: Death Mark

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#402]
### Game Name

Spirit Hunter: Death Mark

### Game code

CUSA12916

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Nothing

### Error

[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = ORBIS_SYSMODULE_JPEG_DEC

### Description

Black screen then crash

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16739637/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions are acceptable
