### ISSUE TITLE
CUSA32884 - Inscryption

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#403]
### Game Name

Inscryption

### Game code

CUSA32884

### Game version

1.00

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Nothing

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceKernelMprotect (nid: vSMAm3cxYTY) called, returning zero to 0x9014a3deb

### Description

Black screen but doesn't seem to crash (waited a few minutes), can be replicated

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16739652/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions are acceptable
