### ISSUE TITLE
CUSA35980 - The Dark Prophecy

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#404]
### Game Name

The Dark Prophecy

### Game code

CUSA35980

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Nothing

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceKernelMprotect (nid: vSMAm3cxYTY) called, returning zero to 0x901525c91

### Description

Black screen, doesn't seem to crash.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16739659/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions are acceptable
