### ISSUE TITLE
CUSA29471 - Dadish

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#405]
### Game Name

Dadish

### Game code

CUSA29471

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

0.2.1

### Current status

Playable

### Error

N/A

### Description

raising vblank driver gets it to run at 280ish fps on my i7 9700k, 2070, and 16gb ddr4. 

### Screenshots

https://youtu.be/c0QuJDHSIho

### Log File

N/A

**Comment by georgemoralis** [comment]
only release versions are acceptable
