### ISSUE TITLE
CUSA33818 - Final Fantasy

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#408]
### Game Name

Final Fantasy

### Game code

CUSA33818

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Nothing

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceKernelMprotect (nid: vSMAm3cxYTY) called, returning zero to 0x901527691

### Description

Black screen no crash

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16739813/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions are acceptable
