### ISSUE TITLE
CUSA44317 - Blasphemous 2

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#409]
### Game Name

Blasphemous 2

### Game code

CUSA44317

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Nothing

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceKernelMprotect (nid: vSMAm3cxYTY) called, returning zero to 0x9015f988e

### Description

Black screen

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16739823/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions are acceptable
