### ISSUE TITLE
CUSA27557 - Blasphemous

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#410]
### Game Name

Blasphemous

### Game code

CUSA27557

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Nothing

### Error

[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 3e+4Iv7IJ8U as accept (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved KuOmgKoqCdY as bind (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved XVL8So3QJUk as connect (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved TXFFFiNldU8 as getpeername (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved RenI1lL1WFk as getsockname (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 6O8EwYOgH9Y as getsockopt (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 4n51s0zEf0c as inet_pton (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved pxnCmagrtao as listen (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved lUk6wrGXyMw as recvfrom (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved hI7oVeOluPM as recvmsg (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved fZOeZIOEmLw as send (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved aNeavPDNKzA as sendmsg (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved oBr313PppNE as sendto (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved fFxGkxF2bVo as setsockopt (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved TUuiYS2kE8s as shutdown (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved TU-d9PfIHPM as socket (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved z0dtnPxYgtg as chmod (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 8nY19bKoiZk as fcntl (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved juWbTNM+8hw as fsync (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved ih4CD9-gghM as ftruncate (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved NN01qLRhiqU as rename (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved VAzswvTOCzI as unlink (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved FN4gaPmuFV8 as write (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved naInUjYt3so as sceKernelRmdir (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 6BpEZuDT7YI as pthread_key_delete (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved QKd0qM58Qes as sceKernelStopUnloadModule (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved UqDGjXA5yUM as munmap (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 18B2NS1y9UU as sceRtcGetCurrentTick (lib: libSceRtc, mod: libSceRtc)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved HoLVWNanBBc as getpid (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 0Cq8ipKr9n0 as sceKernelUtimes (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved iWsFlYMf3Kw as __pthread_cleanup_pop_imp (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 1xvtUVx1-Sg as __pthread_cleanup_push_imp (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved Ez8xjo9UF4E as recv (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved KuOmgKoqCdY as bind (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved TU-d9PfIHPM as socket (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved XVL8So3QJUk as connect (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved fFxGkxF2bVo as setsockopt (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved RenI1lL1WFk as getsockname (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved fZOeZIOEmLw as send (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 3e+4Iv7IJ8U as accept (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved T8fER+tIGgk as select (lib: libScePosix, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved d2g5Ij7EUzo as sceHmdOpen (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved ARhgpXvwoR0 as sceVrTrackerGpuWaitAndCpuProcess (lib: libSceVrTracker, mod: libSceVrTracker)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved knyIhlkpLgE as sceHmdReprojectionSetUserEventEnd (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved TVegDMLaBB8 as sceVrTrackerGpuSubmit (lib: libSceVrTracker, mod: libSceVrTracker)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 1pxQfif1rkE as sceHmdGetDeviceInformationByHandle (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved E+dPfjeQLHI as sceHmdReprojectionSetDisplayBuffers (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved WjHT5TmV0TQ as sceSocialScreenDialogGetResult (lib: libSceSocialScreenDialog, mod: libSceSocialScreenDialog)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved LjdLRysHU6Y as sceHmdReprojectionSetOutputMinColor (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved BEhMn+TyoGA as sceSocialScreenDialogUpdateStatus (lib: libSceSocialScreenDialog, mod: libSceSocialScreenDialog)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved OuygGEWkins as sceHmdReprojectionInitialize (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved OMS9LlcrvBo as sceCameraClose (lib: libSceCamera, mod: libSceCamera)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 8gH1aLgty5I as sceHmdReprojectionStartMultilayer (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved p6n3Npi3YY4 as sceCameraIsAttached (lib: libSceCamera, mod: libSceCamera)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved VQ+5kAqsE2Q as sceCameraSetConfig (lib: libSceCamera, mod: libSceCamera)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved thDt9upZlp8 as sceHmdGetDeviceInformation (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved nmHzU4Gh0xs as sceHmdSetupDialogClose (lib: libSceHmdSetupDialog, mod: libSceHmdSetupDialog)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 6lVRHMV5LY0 as sceHmdSetupDialogGetResult (lib: libSceHmdSetupDialog, mod: libSceHmdSetupDialog)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved K7yhYrsIBPc as sceVrTrackerQueryMemory (lib: libSceVrTracker, mod: libSceVrTracker)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved QkRl7pART9M as sceVrTrackerInit (lib: libSceVrTracker, mod: libSceVrTracker)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved s-J66ar9g50 as sceHmdInitialize315 (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved IBv4P3q1pQ0 as sceVrTrackerTerm (lib: libSceVrTracker, mod: libSceVrTracker)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved Q8skQqEwn5c as sceVrTrackerUnregisterDevice (lib: libSceVrTracker, mod: libSceVrTracker)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved EUCaQtXXYNI as sceVrTrackerRecalibrate (lib: libSceVrTracker, mod: libSceVrTracker)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved NNgiV4T+akU as sceHmdSetupDialogOpen (lib: libSceHmdSetupDialog, mod: libSceHmdSetupDialog)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved BHn83xrF92E as sceCameraOpen (lib: libSceCamera, mod: libSceCamera)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved PEe0R7gBHbc as sceSocialScreenDialogInitialize (lib: libSceSocialScreenDialog, mod: libSceSocialScreenDialog)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved ZrV5YIqD09I as sceHmdReprojectionFinalize (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved zvyKP0Z3UvU as sceVrTrackerGetPlayAreaWarningInfo (lib: libSceVrTracker, mod: libSceVrTracker)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved NPQwYFqi0bs as sceHmdGetFieldOfView (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved NB1Y2kA2jCY as sceHmdSetupDialogInitialize (lib: libSceHmdSetupDialog, mod: libSceHmdSetupDialog)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved z0KtN1vqF2E as sceHmdReprojectionQueryGarlicBuffSize (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved eL54zY-B+-Y as sceSocialScreenDialogOpen (lib: libSceSocialScreenDialog, mod: libSceSocialScreenDialog)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 4ej3RtYH320 as sceSocialScreenDialogClose (lib: libSceSocialScreenDialog, mod: libSceSocialScreenDialog)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved kLUAkN6a1e8 as sceHmdReprojectionQueryOnionBuffSize (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved vzMEkwBQciM as sceHmdReprojectionStop (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved A4KPdcTIVuc as sceSocialScreenDialogTerminate (lib: libSceSocialScreenDialog, mod: libSceSocialScreenDialog)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 9EpRYMy7rHU as sceCameraStart (lib: libSceCamera, mod: libSceCamera)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved U3BVwQl2R5Q as sceCameraIsValidFrameData (lib: libSceCamera, mod: libSceCamera)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved TkcANcGM0s8 as sceHmdReprojectionQueryGarlicBuffAlign (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved mdyFbaJj66M as sceHmdReprojectionClearUserEventStart (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 7as0CjXW1B8 as sceHmdReprojectionSetUserEventStart (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved ktP9j1fN-zE as sceVideoOutConfigureOptionsInitialize_ (lib: libSceVideoOut, mod: libSceVideoOut)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 6biw1XHTSqQ as sceHmdClose (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 76OBvrrQXUc as sceVrTrackerGetResult (lib: libSceVrTracker, mod: libSceVrTracker)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved z-RMILqP6tE as sceHmdTerminate (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved XoeWzXlrnMw as sceVrTrackerGetTime (lib: libSceVrTracker, mod: libSceVrTracker)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved wpeyFwJ+UEI as sceCameraSetVideoSync (lib: libSceCamera, mod: libSceCamera)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved sIh8GwcevaQ as sceVrTrackerRegisterDevice (lib: libSceVrTracker, mod: libSceVrTracker)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved mxgMmR+1Kr0 as sceCameraGetFrameData (lib: libSceCamera, mod: libSceCamera)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved IWybWbR-xvA as sceHmdReprojectionQueryOnionBuffAlign (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved +z4OJmFreZc as sceHmdSetupDialogTerminate (lib: libSceHmdSetupDialog, mod: libSceHmdSetupDialog)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved E0P0sN-wy+4 as sceVrTrackerResetOrientationRelative (lib: libSceVrTracker, mod: libSceVrTracker)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved 9fvHMUbsom4 as sceVrTrackerUpdateMotionSensorData (lib: libSceVrTracker, mod: libSceVrTracker)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved iGNNpDDjcwo as sceHmdReprojectionUnsetDisplayBuffers (lib: libSceHmd, mod: libSceHmd)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved Ud7j3+RDIBg as sceHmdSetupDialogUpdateStatus (lib: libSceHmdSetupDialog, mod: libSceHmdSetupDialog)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved zk6c65xoyO0 as sceNpWebApiCreateContextA (lib: libSceNpWebApi, mod: libSceNpWebApi)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved CQtPRSF6Ds8 as sceNpWebApiReadData (lib: libSceNpWebApi, mod: libSceNpWebApi)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved noQgleu+KLE as sceNpWebApiDeleteRequest (lib: libSceNpWebApi, mod: libSceNpWebApi)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved G3AnLNdRBjE as sceNpWebApiInitialize (lib: libSceNpWebApi, mod: libSceNpWebApi)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved rdgs5Z1MyFw as sceNpWebApiCreateRequest (lib: libSceNpWebApi, mod: libSceNpWebApi)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved KjNeZ-29ysQ as sceNpWebApiSendRequest2 (lib: libSceNpWebApi, mod: libSceNpWebApi)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved xQeIryTX7dY as sceRemoteplayApprove (lib: libSceRemoteplay, mod: libSceRemoteplay)
[Core.Linker] <Error> linker.cpp:Resolve:279: Linker: Stub resolved ca7v6Cxulzs as sceKernelSetGPO (lib: libkernel, mod: libkernel)

### Description

Crash

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16739827/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions are acceptable
