### ISSUE TITLE
CUSA13632 - Hollow Knight

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#411]
### Game Name

Hollow Knight

### Game code

CUSA13632

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Nothing

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: memset (nid: 8zTFvBIAIN8) called, returning zero to 0x92001eb46

### Description

Crash

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16739835/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions are acceptable
