### ISSUE TITLE
CUSA27386 - Arcade Paradise

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#412]
### Game Name

Arcade Paradise

### Game code

CUSA27386

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.2.0

### Current status

Nothing

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceKernelMprotect (nid: vSMAm3cxYTY) called, returning zero to 0x9014ab986

### Description

Black screen

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16739873/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions are acceptable
