### ISSUE TITLE
CUSA06739 - Death Squared

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#414]
### Game Name

Death Squared

### Game code

CUSA06739

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.2.0

### Current status

Boots

### Error

[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitDone:2139: called
[Tty] <Info> libkernel.cpp:ps4__write:210: Forcing submitDone to avoid TRC R4089 breach

repeats indefinitely ^^

### Description

loads enough to show afterburners gui, but gets stuck on a black screen

### Screenshots

![image](https://github.com/user-attachments/assets/8d394e29-578a-494c-9188-037f2c574941)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16739935/shad_log.txt)

**Comment by vladmikhalin** [comment]
There is no singular 0.2.1 version that was released. Please stop submitting reports for this version.

**Comment by georgemoralis** [comment]
duplicated
