### ISSUE TITLE
CUSA16870 - Five Nights at Freddy's (shad v0.2.0)

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#435]
### Game Name

Five Nights at Freddy's

### Game code

CUSA16870

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.20

### Current status

Nothing

### Error

several, read in log

### Description

crashes

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16742100/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicated
