### ISSUE TITLE
[Debug] <Critical> liverpool.cpp:ProcessGraphics:495: Unreachable code! Unknown PM4 type 3 opcode 0x24 with count 4 - BLOODBORNE

### ISSUE THREAD

**Issue by zaK081597** [shadps4-emu/shadps4-game-compatibility#529]
### Game Name

BLOODBORNE

### Game code

CUSA03173

### Game version

1.09

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Playable

### Error

GAME CRASH

### Description

Game crashes after character creation and loading ingame cutscene

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16809055/shad_log.txt)

**Comment by Karmin28** [comment]
was a fix for this found at any point?
and if yes, how can i fix it too?

**Comment by zaK081597** [comment]
yes, you should try the newest foul tarnished build it has fixed more of
these crashes

https://github.com/Foul-Tarnished/shadPS4/actions/runs/10753285567

also disabling the sfx helps a lot for the moment, try the shadows mod and
also the sounds mod, it will help more likely to be an actual playable
experience

*XxMilkxX*
