### ISSUE TITLE
CUSA08790 - GUNDAM VERSUS

### ISSUE THREAD

**Issue by Ghaleon7771** [shadps4-emu/shadps4-game-compatibility#537]
### Game Name

GUNDAM VERSUS

### Game code

CUSA08790

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Nothing

### Error

The game crashes after booting, black screen and then the emulator closes.

### Description

Crashes on boot.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16843859/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions pls
