### ISSUE TITLE
CUSA25503 - MADE IN ABYSS BINARY STAR FALLING INTO DARKNESS

### ISSUE THREAD

**Issue by DzikiSzogun** [shadps4-emu/shadps4-game-compatibility#539]
### Game Name

MADE IN ABYSS BINARY STAR FALLING INTO DARKNESS

### Game code

CUSA18642

### Game version

01.03

### Used emulator's version (only released versions are acceptable)

v0.2.0

### Current status

Nothing

### Error

Game not start and only appears a black screen
Nothing happen after. Just stay in black screen
But didn't close shadps4

### Description

Crashes on boot.
Blackscreen

### Screenshots

![image](https://github.com/user-attachments/assets/a6dc54ad-004f-4738-a72e-bbff9a691aa2)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16859040/shad_log.txt)

**Comment by georgemoralis** [comment]
wrong game id
