### ISSUE TITLE
Freezes and crashes on Bloodborne

### ISSUE THREAD

**Issue by ZethrasGorgoth** [shadps4-emu/shadps4-game-compatibility#540]
### Game Name

Bloodborne

### Game code

CUSA03173

### Game version

v01.09

### Used emulator's version (only released versions are acceptable)

0.2.0

### Current status

Ingame

### Error

No error message

### Description

The game crashes right after the first cutscene, where you get prompted to "sign the contract" and as soon as it gets to the character creation screen fps instantly drop to 15, the game freezes and soon after it crashes. This is pretty consistent along the board, so to speak.

In some rare occation, I've been able to get past the CSS and into the second cutscene, but as soon as I skipped it the issue presented itself again. It also happens in the character selection screen after selecting "load game". 

As stated in the prompt here, I'm using the 0.2.0 version of the emulator, but since I have a full AMD setup (both cpu and gpu, namely Ryzen 5 2600 and 5700 XT) I also tried installing the 0.2.1 version, named bb-hacks, to no avail

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16868845/shad_log.txt)

**Comment by georgemoralis** [comment]
already exist
