### ISSUE TITLE
CUSA00223-inFamous Second Son

### ISSUE THREAD

**Issue by Wakelogger** [shadps4-emu/shadps4-game-compatibility#543]
### Game Name

inFamous Second Son

### Game code

CUSA00223

### Game version

v01.07

### Used emulator's version (only released versions are acceptable)

v0.2.0

### Current status

Nothing

### Error

[Lib.PlayGo] <Error> playgo.cpp:scePlayGoGetLocus:53: (STUBBED)called handle = 1, chunkIds = 19, numberOfEntries = 52
[Lib.PlayGo] <Error> playgo.cpp:scePlayGoGetLocus:53: (STUBBED)called handle = 1, chunkIds = 19, numberOfEntries = 52
[Lib.PlayGo] <Error> playgo.cpp:scePlayGoGetLocus:53: (STUBBED)called handle = 1, chunkIds = 19, numberOfEntries = 52
[Lib.PlayGo] <Error> playgo.cpp:scePlayGoGetLocus:53: (STUBBED)called handle = 1, chunkIds = 19, numberOfEntries = 52
[Lib.PlayGo] <Error> playgo.cpp:scePlayGoGetLocus:53: (STUBBED)called handle = 1, chunkIds = 19, numberOfEntries = 52
[Lib.PlayGo] <Error> playgo.cpp:scePlayGoGetLocus:53: (STUBBED)called handle = 1, chunkIds = 19, numberOfEntries = 52

### Description

Game is a black screen, with this replicating.

### Screenshots

![Screenshot 2024-09-05 141310](https://github.com/user-attachments/assets/d670035f-0a14-4836-8f4d-941c422a3432)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16889165/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicated

**Comment by Wakelogger** [comment]
@georgemoralis can you write which issue it is the duplicate of? So i can follow it and see if it gets fixed. I’m sorry for the mention

**Comment by BERTOLINISKI** [comment]
[https://github.com/shadps4-emu/shadps4-game-compatibility/issues/314](url)
