### ISSUE TITLE
CUSA01369 - Limbo

### ISSUE THREAD

**Issue by rodrijag92** [shadps4-emu/shadps4-game-compatibility#545]
### Game Name

Limbo

### Game code

CUSA01369

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Ingame

### Error

N/A

### Description

Minor graphical issue and slow FPS

specs:
Ryzen 7 5700u
Vega 8 (1900 MHz)
8gb ddr4

### Screenshots

![image](https://github.com/user-attachments/assets/c8743541-5393-4ebc-a82d-8438b032bab9)
![image](https://github.com/user-attachments/assets/0e111fd3-a84d-477a-9cdf-8e05fff7354e)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16902025/shad_log.txt)

**Comment by rodrijag92** [comment]
https://github.com/user-attachments/assets/6227d8d4-d9d1-431c-b7a4-d394163b79c5

**Comment by georgemoralis** [comment]
only release versions pls
