### ISSUE TITLE
CUSA02516 - Mega Man Legacy Collection

### ISSUE THREAD

**Issue by rodrijag92** [shadps4-emu/shadps4-game-compatibility#546]
### Game Name

Mega Man Legacy Collection

### Game code

CUSA02516

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Menus

### Error

The game takes a long time to start
Graphical errors in the menu
No sound
The game itself appears functional

### Description

specs:
Ryzen 7 5700u
Vega 8 (1900 MHz)
8gb ddr4

### Screenshots

![image](https://github.com/user-attachments/assets/cca46c44-d632-4f01-a94f-184246a439e3)
![image](https://github.com/user-attachments/assets/85bb0dba-0ad5-4c75-8907-eab6d2a60d14)
![image](https://github.com/user-attachments/assets/4ce8f908-6396-4671-88ac-6dd66be1f149)
![image](https://github.com/user-attachments/assets/f01a1f20-ca8c-4227-ba2b-78c56d501b52)
![image](https://github.com/user-attachments/assets/ad4bca60-b876-4b74-adb2-c46b3dceac83)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16902397/shad_log.txt)

**Comment by StevenMiller123** [comment]
Only test on release versions (currently, that's version 0.2.0).

**Comment by georgemoralis** [comment]
only release versions pls
