### ISSUE TITLE
CUSA00897 - InFamous: First Light

### ISSUE THREAD

**Issue by Godefrido** [shadps4-emu/shadps4-game-compatibility#567]
### Game Name

InFamous: First Light

### Game code

CUSA00897

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.2.0

### Current status

Nothing

### Error

[Lib.PlayGo] <Error> playgo.cpp:scePlayGoGetLocus:53: (STUBBED)called handle = 1, chunkIds = 3, numberOfEntries = 50
[Lib.Pad] <Error> pad.cpp:scePadInit:189: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetInit:761: (DUMMY) called
[Lib.NetCtl] <Error> netctl.cpp:sceNetCtlInit:242: (STUBBED) called
[Lib.NetCtl] <Error> netctl.cpp:sceNetCtlGetState:217: (STUBBED) called
[Lib.PlayGo] <Error> playgo.cpp:scePlayGoGetLocus:53: (STUBBED)called handle = 1, chunkIds = 3, numberOfEntries = 50
[Lib.PlayGo] <Error> playgo.cpp:scePlayGoGetLocus:53: (STUBBED)called handle = 1, chunkIds = 3, numberOfEntries = 50
[Lib.PlayGo] <Error> playgo.cpp:scePlayGoGetLocus:53: (STUBBED)called handle = 1, chunkIds = 3, numberOfEntries = 50

### Description

Trying to open the game results in nothing but a black screen. The last error listed repeats in a loop.

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16919447/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicate
