### ISSUE TITLE
CUSA01752 - Dead Island Retro Revenge

### ISSUE THREAD

**Issue by Mundov** [shadps4-emu/shadps4-game-compatibility#582]
### Game Name

Dead Island: Retro Revenge

### Game code

CUSA01752

### Game version

v01.01

### Used emulator's version (only released versions are acceptable)

v0.2.1

### Current status

Playable

### Error

none

### Description

Intel Xeon E5-2673 v3
Nvidia GTX 1050TI
16GB RAM DDR4

### Screenshots

![di02](https://github.com/user-attachments/assets/f9b603eb-0aba-4a6c-83d2-ab0da0ac82cc)

![di01](https://github.com/user-attachments/assets/2d338650-7e1a-4b72-b167-30187c9df6fd)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16957887/shad_log.txt)

**Comment by Mundov** [comment]
https://github.com/user-attachments/assets/34493a23-eb65-4ecd-a27b-516654fb5c68

**Comment by georgemoralis** [comment]
only reports for release versions is acceptable :D You can recommit once 0.3.0 is ready
