### ISSUE TITLE
CUSA36843/CUSA36842 - Red Dead Redemption

### ISSUE THREAD

**Issue by JasonBrodyFC** [shadps4-emu/shadps4-game-compatibility#589]
### Game Name

Red Dead Redemption

### Game code

CUSA36843

### Game version

1.00/1.04

### Used emulator's version (only released versions are acceptable)

0.2.1 WIP

### Current status

Ingame

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x90006fa45
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x90006fa45
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070add
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070b01
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070add
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070b01
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070add
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070b01
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070add
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070b01
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070add
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070b01
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070add
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070b01
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070add
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070b01
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070add
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070b01
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070add
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2VoiceControl (nid: uu94irFOGpA) called, returning zero to 0x900070b01
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:452: name=d11mutex, result=0
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x90006fa45
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x90006fa45
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceNgs2SystemRender (nid: i0VnXM-C9fc) called, returning zero to 0x90006fa45

### Description

Hello, it's been 1 week now with 10/15 version of 0.2.0 as 0.2.1 that I try without success on my pc with windows 10 22H2 a functioning of Red dead redemption that works but crashes when I advance in a goal that leads to a cinematic.

### Screenshots

![rdr1](https://github.com/user-attachments/assets/4d0d1440-c275-4247-9fd0-8ad5f2cbda28)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17003520/shad_log.txt)

**Comment by TheCoolPup** [comment]
STABLE BUILDS ONLY

**Comment by Arthurfogo7** [comment]
Oh, nice, it's really working, I thought this emulator only allowed us to play Bloodborne.

**Comment by georgemoralis** [comment]
duplicate and wrong version
