### ISSUE TITLE
CUSA04518 - Hatsune Miku Project DIVA X

### ISSUE THREAD

**Issue by PDAFTS** [shadps4-emu/shadps4-game-compatibility#630]
### Game Name

Hatsune Miku Project DIVA X

### Game code

CUSA04518

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.3.0

### Current status

Nothing

### Error

![image](https://github.com/user-attachments/assets/c03606ed-ccb6-4758-855d-42192fe3e16f)

### Description

crashing, black screen at booting

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17105063/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicated #49
