### ISSUE TITLE
CUSA07753  - アイドルマスター ステラステージ IDOLM@STER STELLA STAGE

### ISSUE THREAD

**Issue by ToastyBuns3939** [shadps4-emu/shadps4-game-compatibility#632]
### Game Name

IDOLM@STER STELLA STAGE

### Game code

CUSA07753 

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v.0.3.0

### Current status

Nothing

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: getpid (nid: HoLVWNanBBc) called, returning zero to 0x9008fc1e1

the rest can be found in the log file

### Description

Game crashes on launch

### Screenshots

![image](https://github.com/user-attachments/assets/e809c00e-7bc9-4cc1-acc4-eeff2f779114)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17107755/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicated #380
