### ISSUE TITLE
CUSA00437 - Ultratron

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#637]
### Game Name

Ultratron

### Game code

CUSA00437

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.3.0

### Current status

Boots

### Error

[Debug] <Critical> image_info.cpp:operator():275: Assertion Failed!

### Description

Gets to point shown in screenshot then crashes with error above

### Screenshots

![image](https://github.com/user-attachments/assets/760cc343-2059-4444-a364-a862dc44d873)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17109232/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicated #112
