### ISSUE TITLE
CUSA02366 - Beach Buggy Racing

### ISSUE THREAD

**Issue by SNKWiz** [shadps4-emu/shadps4-game-compatibility#638]
### Game Name

Beach Buggy Racing

### Game code

CUSA02366

### Game version

v01.02

### Used emulator's version (only released versions are acceptable)

0.3.0

### Current status

Nothing

### Error

[Debug] <Critical> signals.cpp:SignalHandler:102: Unreachable code!
Unhandled access violation at code address 0x90011bb06: Read from address 0xc

See log.

### Description

On Mac it crashes a right after displaying ESRB screen

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17109642/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicate #592
