### ISSUE TITLE
CUSA10454 - Dragon's Crown Pro

### ISSUE THREAD

**Issue by iChris4** [shadps4-emu/shadps4-game-compatibility#645]
### Game Name

Dragon's Crown Pro

### Game code

CUSA10454

### Game version

01.00

### Used emulator's version (only released versions are acceptable)

0.3.0

### Current status

Playable

### Error

see log

### Description

Runs great, have minor graphical issues in the menu

### Screenshots

![Screenshot 2024-09-25 001712](https://github.com/user-attachments/assets/9b80c381-b816-4ba4-af5d-acdd9ce23cac)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17121799/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicate pls update #170
