### ISSUE TITLE
Bloodborne - CUSA03173

### ISSUE THREAD

**Issue by yaya54840** [shadps4-emu/shadps4-game-compatibility#651]
### Game Name

Bloodborne

### Game code

CUSA03173

### Game version

1.09

### Used emulator's version (only released versions are acceptable)

0.3.0

### Current status

Ingame

### Error

See log

### Description

We are in the game with different patches 
Windows 11 pro

### Screenshots

![Capture d'écran 2024-09-25 095832](https://github.com/user-attachments/assets/ace2c886-ed99-4927-98a4-a654ef130f57)
![Capture d'écran 2024-09-25 095915](https://github.com/user-attachments/assets/691d0dc6-a326-42bd-a3d6-faee6081f325)
![Capture d'écran 2024-09-25 100216](https://github.com/user-attachments/assets/14b19600-9b6b-44db-9a2a-d1c7ece2e98a)

### Log File

[shad_log.zip](https://github.com/user-attachments/files/17127500/shad_log.zip)

**Comment by Cyclizar** [comment]
Merge with #71

**Comment by georgemoralis** [comment]
yah you should add it on #71
