### ISSUE TITLE
PAC-MAN 256 - CUSA05026

### ISSUE THREAD

**Issue by AYoutuber807** [shadps4-emu/shadps4-game-compatibility#653]
### Game Name

PAC-MAN 256

### Game code

CUSA05026

### Game version

1.01

### Used emulator's version (only released versions are acceptable)

0.3.0

### Current status

Nothing

### Error

See log.

### Description

Only Black Screen.

### Screenshots

![image](https://github.com/user-attachments/assets/9826a5c4-120e-49bd-b923-af65e2731eeb)

### Log File

[log.zip](https://github.com/user-attachments/files/17133632/log.zip)

**Comment by Cyclizar** [comment]
merge with #425

**Comment by georgemoralis** [comment]
duplicate
