### ISSUE TITLE
CUSA33388 - RESIDENT EVIL 4 (EU)

### ISSUE THREAD

**Issue by PaulStranger** [shadps4-emu/shadps4-game-compatibility#654]
### Game Name

RESIDENT EVIL 4

### Game code

CUSA33388

### Game version

01.11

### Used emulator's version (only released versions are acceptable)

0.3.0

### Current status

Nothing

### Error

[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved kbw4UHHSYy0 as __pthread_cxa_finalize (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved djxxOmW6-aw as __progname (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved rNhWz+lvOMU as _sceKernelSetThreadDtors (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved pB-yGZ2nQ9o as _sceKernelSetThreadAtexitCount (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved WhCc1w3EhSI as _sceKernelSetThreadAtexitReport (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved zE-wXIZjLoM as sceKernelDebugRaiseExceptionOnReleaseMode (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved Tz4RNUCBbGI as _sceKernelRtldThreadAtexitIncrement (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved 8OnWXlgQlvo as _sceKernelRtldThreadAtexitDecrement (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved How7B8Oet6k as scePthreadGetname (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved crb5j7mkk1c as _is_signal_return (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved PrdHuuDekhY as scePthreadKeyDelete (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved VADc3MNQ3cM as signal (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved NhpspxdjEKU as _nanosleep (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved py6L8jiVAN8 as sceKernelGetSanitizerMallocReplaceExternal (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved Wl2o5hOVZdw as sceKernelPrintBacktraceWithModuleInfo (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved -YTW+qXc3CQ as sceKernelInternalMemoryGetModuleSegmentInfo (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved 3k6kx-zOOSQ as sceKernelMlock (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved jh+8XiK4LeE as sceKernelIsAddressSanitizerEnabled (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved c7ZnT7V1B98 as rmdir (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved 0Cq8ipKr9n0 as sceKernelUtimes (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved WlyEA-sLDf0 as sceKernelTruncate (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved fgIsQ10xYVA as sceKernelChmod (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved bnZxYgAFeA0 as sceKernelGetSanitizerNewReplaceExternal (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved kbw4UHHSYy0 as __pthread_cxa_finalize (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved Fjc4-n1+y2g as __elf_phdr_match_addr (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved 6Z83sYWFlA8 as _exit (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved hHlZQUnlxSM as getrusage (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved ZT4ODD2Ts9o as Need_sceLibcInternal (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved H2e8t5ScQGc as __cxa_finalize (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved 2sWzhYqFH4E as _Stdout (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved H2e8t5ScQGc as __cxa_finalize (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved Q2V+iqvjgC0 as vsnprintf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved hcuQgD53UxM as printf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved fJgP+wqifno as Unknown !!! (lib: libSceDiscMap, mod: libSceDiscMap)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved lbQKqsERhtE as sceDiscMapIsRequestOnHDD (lib: libSceDiscMap, mod: libSceDiscMap)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved 8zTFvBIAIN8 as memset (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved Q3VBxCXhUHs as memcpy (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved GMpvxPFW924 as vprintf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved MUjC4lbHrK4 as fflush (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved n7AepwR0s34 as mktime (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved wLlFkwG9UcQ as time (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved efhK-YSUYYQ as localtime (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved 1mecP7RgI2A as gmtime (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved 5bBacGLyLOs as gmtime_s (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved naInUjYt3so as sceKernelRmdir (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved WlyEA-sLDf0 as sceKernelTruncate (lib: libkernel, mod: libkernel)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved gQX+4GDQjpM as malloc (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved tIhsqj0qsFE as free (lib: libSceLibcInternal, mod: libSceLibcInternal)

### Description

I just click "Play", a black screen appears. After 4-5 seconds, the emulator automatically terminates with a critical error.

### Screenshots

![Untitled-1](https://github.com/user-attachments/assets/a20fa5bf-1bab-4179-af52-a2954f692faf)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17135681/shad_log.txt)

**Comment by Cyclizar** [comment]
duplicate #612 (same cusa too), might want to merge

**Comment by georgemoralis** [comment]
duplicate
