### ISSUE TITLE
DYSMANTLE

### ISSUE THREAD

**Issue by Mored4u** [shadps4-emu/shadps4-game-compatibility#667]
### Game Name

DYSMANTLE

### Game code

CUSA15128

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.3.0

### Current status

Menus

### Operating System

Windows

### Error

only menus with perfect sound

### Description

only menus after click play ShadPS4 Closed

### Screenshots

![image](https://github.com/user-attachments/assets/88463210-1857-4853-bd87-d079db7dfa7f)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17146872/shad_log.txt)

**Comment by Mored4u** [comment]
Game Name
DYSMANTLE

Game code
CUSA15128

Game version
v01.08

Used emulator's version (only released versions are acceptable)
v0.3.0

Current status
nothing

Operating System
Windows

Error
nothing

Description
nothing then ShadPS4 Closed

Screenshots
![image](https://github.com/user-attachments/assets/27686a83-cea0-4033-8d96-2afedcc4c188)

Log File
[shad_log.txt](https://github.com/user-attachments/files/17146908/shad_log.txt)

**Comment by Mored4u** [comment]
Game Name
DYSMANTLE

Game code
CUSA15128

Game version
v01.00

Used emulator's version (only released versions are acceptable)
v0.3.1 #1080

Current status
Playable

Operating System
Windows

Error
No issue

Description
Playable

Screenshots
![image](https://github.com/user-attachments/assets/50e0c35f-9338-48db-af58-d0762505785d)
![image](https://github.com/user-attachments/assets/c9acd4c8-9c20-417e-b0bd-b2cd47d69e4d)
![image](https://github.com/user-attachments/assets/e126b3ee-fb6a-4699-9add-350ba5bb9e8c)
![image](https://github.com/user-attachments/assets/73940f7c-2b57-4351-9a71-f4a78af406d2)

Log File
[shad_log.txt](https://github.com/user-attachments/files/17146948/shad_log.txt)

**Comment by Cyclizar** [comment]
very cool, might want to add the CUSA to the thread name though

**Comment by tomnic79** [comment]
I've got a systematic crash as soon as I walk after the campfire.
