### ISSUE TITLE
CUSA05070 - YAKUZA 0

### ISSUE THREAD

**Issue by az511** [shadps4-emu/shadps4-game-compatibility#690]
### Game Name

YAKUZA 0

### Game code

CUSA05070 

### Game version

v1.05

### Used emulator's version (only released versions are acceptable)

v0.3.1

### Current status

Ingame

### Operating System

Windows

### Error

[Debug] <Critical> liverpool_to_vk.h:PromoteFormatToDepth:79: Unreachable code!

### Description

white screen pops up when fighting and cutscenes. crashes when pressing tringle or x while fighting. fps drop when looking at at big areas. everything else seems good

### Screenshots

![Screenshot (5)](https://github.com/user-attachments/assets/65c644d7-63ca-40e6-91d6-8c616ac0c05f)
![Screenshot (4)](https://github.com/user-attachments/assets/909050d2-f8e9-4ec5-b0a7-3a038741282f)
![Screenshot (6)](https://github.com/user-attachments/assets/d9408975-efa8-4466-bf13-240aacc35d12)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17160869/shad_log.txt)

**Comment by Hermiten** [comment]
Please only do test on major release like 0.4
Thanks you
