### ISSUE TITLE
CUSA02193 - Hot Shots Tennis

### ISSUE THREAD

**Issue by az511** [shadps4-emu/shadps4-game-compatibility#744]
### Game Name

Hot Shots Tennis

### Game code

CUSA02193 

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.3.1

### Current status

Nothing

### Operating System

Windows

### Error

[Core.Linker] <Error> linker.cpp:InitTlsForThread:373: TLS user malloc called, using std::malloc
[Kernel.Pthread] <Error> thread_management.cpp:scePthreadSetschedparam:1484: (STUBBED) called policy=1, sched_priority=448
[Lib.UserService] <Info> userservice.cpp:sceUserServiceGetInitialUser:494: called
[Tty] <Info> libkernel.cpp:ps4__write:221: x-host  [   0.032sec] Setting PS4 Title ID : OLYP20231_00
[Lib.NpManager] <Error> np_manager.cpp:sceNpSetNpTitleId:1989: (STUBBED) called
[Tty] <Info> libkernel.cpp:ps4__write:221: x-save  [   0.033sec] Creating new Instance for SaveData, key=SCUS-976101
[Kernel.Vmm] <Warning> memory_management.cpp:sceKernelGetDirectMemorySize:19: called
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:451: name=SaveDataReqQueue, result=0
[Kernel.Vmm] <Info> memory_management.cpp:sceKernelAllocateDirectMemory:51: searchStart = 0x0, searchEnd = 0x120000000, len = 0x70000, alignment = 0x0, memoryType = 0x0, physAddrOut = 0x10008000
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCreate:1042: thread create name = SaveDataInBackground
[Core.Linker] <Error> linker.cpp:InitTlsForThread:373: TLS user malloc called, using std::malloc
[Kernel.Pthread] <Error> thread_management.cpp:scePthreadSetschedparam:1484: (STUBBED) called policy=1, sched_priority=83

### Description

nothing

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17207066/shad_log.txt)

**Comment by Hermiten** [comment]
Please use major release version to do test
