### ISSUE TITLE
crash team racing nitro fueled error

### ISSUE THREAD

**Issue by Morok999** [shadps4-emu/shadps4-game-compatibility#905]
### Game Name

Crash team racing nitro - fueled

### Game code

CUSA14876

### Game version

1.0.1

### Used emulator's version (only released versions are acceptable)

0.3.0

### Current status

Boots

### Operating System

Windows

### Error

[Core.Linker] <Error> linker.cpp:InitTlsForThread:365: TLS user malloc called, using std::malloc
[Kernel.Pthread] <Error> thread_management.cpp:scePthreadAttrSetschedpolicy:286: policy=1 not supported by winpthreads
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = ORBIS_SYSMODULE_SAVE_DATA_DIALOG

### Description

As soon as I press start I get a bunch of errors

### Screenshots

![Снимок экрана 2024-10-16 191905](https://github.com/user-attachments/assets/ba6d12ac-2091-4f05-bdbe-78139e743c37)

### Log File

[Uploading shad_log.txt…]()

**Comment by Cyclizar** [comment]
rename to:

CUSA14876 - Crash™ Team Racing Nitro-Fueled

and reupload the log, or itll get taken down
