### ISSUE TITLE
CUSA35521 - MLB The Show 23

### ISSUE THREAD

**Issue by anthr76** [shadps4-emu/shadps4-game-compatibility#913]
### Game Name

MLB The Show 23

### Game code

CUSA35521

### Game version

v1.21

### Used emulator's version (only released versions are acceptable)

v0.3.1

### Current status

Playable

### Operating System

Windows

### Error

Doesn't currently get past screenshot

### Description

Hangs on startup shadps4 needs to be forcefully terminated 

### Screenshots

![image](https://github.com/user-attachments/assets/c5bc107a-c049-4a9c-b07e-58b21fe14815)

### Log File

https://gist.github.com/anthr76/14930dbc3cea258ff208a4ee99d4f35f

**Comment by georgemoralis** [comment]
v0.3.1 is WIP version , only released version permited
