### ISSUE TITLE
CUSA01127 - P.T.

### ISSUE THREAD

**Issue by pepperdogged** [shadps4-emu/shadps4-game-compatibility#914]
### Game Name

P.T.

### Game code

CUSA01127

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.3.0

### Current status

Nothing

### Operating System

Windows

### Error

[Common.Filesystem] <Error> io_file.cpp:Open:196: Failed to open the file at path=
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = ORBIS_SYSMODULE_VIDEO_RECORDING
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = ORBIS_SYSMODULE_SCREEN_SHOT
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = 
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceGameLiveStreamingInitialize (nid: kvYEw2lBndk) called, returning zero to 0x900a6c71c
[Core.Linker] <Error> linker.cpp:InitTlsForThread:365: TLS user malloc called, using std::malloc
[Core] <Error> stubs.cpp:CommonStub:42: Stub: select (nid: T8fER+tIGgk) called, returning zero to 0x900a76259

### Description

Black screen

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17527798/shad_log.txt)

**Comment by Cyclizar** [comment]
lmao

**Comment by KnuXles** [comment]
This issue already existed:
https://github.com/shadps4-emu/shadps4-game-compatibility/issues/2
