### ISSUE TITLE
CUSA10069 - Detention

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#916]
### Game Name

Detention

### Game code

CUSA10069

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.3.0

### Current status

Nothing

### Operating System

Windows

### Error

[Tty] <Info> libkernel.cpp:ps4__write:222: Forcing submitDone to avoid TRC R4089 breach

### Description

black screen 

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17528985/shad_log.txt)

**Comment by georgemoralis** [comment]
duplicated #224
