### ISSUE TITLE
CUSA32836 - NARUTO X BORUTO Ultimate Ninja STORM CONNECTIONS

### ISSUE THREAD

**Issue by illyazru** [shadps4-emu/shadps4-game-compatibility#942]
### Game Name

NARUTO X BORUTO Ultimate Ninja STORM CONNECTIONS

### Game code

CUSA32836

### Game version

1.00

### Used emulator's version (only released versions are acceptable)

0.4.1

### Current status

Nothing

### Operating System

Windows

### Error

[Lib.UserService] <Warning> userservice.cpp:sceUserServiceInitialize:1126: (dummy) called
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = ORBIS_SYSMODULE_MOUSE
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:47: (DUMMY) called module = ORBIS_SYSMODULE_LIBIME
[Lib.Pad] <Error> pad.cpp:scePadInit:203: (STUBBED) called
[Lib.Pad] <Info> pad.cpp:scePadOpen:248: (DUMMY) called user_id = 1 type = 0 index = 0
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceMouseInit (nid: Qs0wWulgl7U) called, returning zero to 0x9014fc033
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceMouseOpen (nid: RaqxZIf6DvE) called, returning zero to 0x9014fc094
[Lib.Ime] <Error> ime.cpp:sceImeKeyboardOpen:262: (STUBBED) called
[Lib.Ime] <Error> ime.cpp:sceImeKeyboardOpen:262: (STUBBED) called
[Lib.Ime] <Error> ime.cpp:sceImeKeyboardOpen:262: (STUBBED) called
[Lib.Ime] <Error> ime.cpp:sceImeKeyboardOpen:262: (STUBBED) called
[Lib.Ime] <Error> ime.cpp:sceImeKeyboardOpen:262: (STUBBED) called
[Lib.Ime] <Error> ime.cpp:sceImeKeyboardOpen:262: (STUBBED) called
[Lib.Ime] <Error> ime.cpp:sceImeKeyboardOpen:262: (STUBBED) called
[Lib.Ime] <Error> ime.cpp:sceImeKeyboardOpen:262: (STUBBED) called

### Description

This game was going ingame in previous versions (don't know which version), now it doesn't boot anymore.

### Screenshots

![Captura de tela 2024-10-31 194228](https://github.com/user-attachments/assets/271e71d8-ab0c-4592-9f9b-04c8c99052e4)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17594030/shad_log.txt)

**Comment by georgemoralis** [comment]
only released versions pls
