### ISSUE TITLE
CUSA00010 - Assassin's Creed® IV Black Flag

### ISSUE THREAD

**Issue by illyazru** [shadps4-emu/shadps4-game-compatibility#943]
### Game Name

Assassin's Creed® IV Black Flag

### Game code

CUSA00010

### Game version

v01.04

### Used emulator's version (only released versions are acceptable)

v0.4.1

### Current status

Nothing

### Operating System

Windows

### Error

The game doesn't show any errors, just crashes.

### Description

The game doesn't boot, just crashes.

### Screenshots

![Captura de tela 2024-10-31 205303](https://github.com/user-attachments/assets/f788fcf8-60e5-4a9b-b8d9-38cd9bcde073)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17594295/shad_log.txt)

**Comment by georgemoralis** [comment]
released version only thanks!
