### ISSUE TITLE
CUSA13801 - Sekiro™: Shadows Die Twice

### ISSUE THREAD

**Issue by illyazru** [shadps4-emu/shadps4-game-compatibility#944]
### Game Name

Sekiro™: Shadows Die Twice

### Game code

CUSA13801

### Game version

v01.00

### Used emulator's version (only released versions are acceptable)

v0.4.1

### Current status

Nothing

### Operating System

Windows

### Error

[Debug] <Critical> memory.cpp:operator():655: Assertion Failed!
Mapping cannot fit inside free region: size = 0xc0000000

### Description

Game just crashes at the start.

### Screenshots

![Captura de tela 2024-10-31 222923](https://github.com/user-attachments/assets/e9a7fd32-af58-46f5-8465-ab839b56adf5)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17594929/shad_log.txt)

**Comment by Cyclizar** [comment]
duplicate #688
