### ISSUE TITLE
CUSA02172 - Journey™ Collector’s Edition

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadps4-game-compatibility#947]
### Game Name

Journey™ Collector’s Edition

### Game code

CUSA02172

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.4.0

### Current status

Nothing

### Operating System

Windows

### Error

[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:399: Compiling fs shader 0x57bcedab 
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:399: Compiling vs shader 0x6025d17 
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:399: Compiling vs shader 0x6025d17 
[Debug] <Critical> liverpool_to_vk.cpp:operator():650: Assertion Failed!
Unknown data_format=49 and num_format=4

### Description

crashes

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17595074/shad_log.txt)

**Comment by georgemoralis** [comment]
there is an entry at https://github.com/shadps4-emu/shadps4-game-compatibility/issues/899
pls update that

**Comment by Cyclizar** [comment]
mb
