### ISSUE TITLE
CUSA14409 - Castle Crashers Remastered

### ISSUE THREAD

**Issue by az511** [shadps4-emu/shadps4-game-compatibility#951]
### Game Name

Castle Crashers Remastered

### Game code

CUSA14409 

### Game version

v1.04 

### Used emulator's version (only released versions are acceptable)

v0.4.1

### Current status

Playable

### Operating System

Windows

### Error

error in log but playable ?

### Description

playable. Vblank speeds up game

### Screenshots

![Screenshot (7)](https://github.com/user-attachments/assets/32e4da53-c315-4378-a1c0-2e2e17ed5d81)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17601442/shad_log.txt)

**Comment by georgemoralis** [comment]
released version only thanks
