### ISSUE TITLE
CUSA00264 - EA SPORTS™ UFC®

### ISSUE THREAD

**Issue by Lepexa-cell** [shadps4-emu/shadps4-game-compatibility#952]
### Game Name

EA SPORTS™ UFC®

### Game code

CUSA00264

### Game version

v01.08

### Used emulator's version (only released versions are acceptable)

v0.4.1 WIP

### Current status

Nothing

### Operating System

Windows

### Error

EA SPORTS™ UFC® is just a black screen

### Description

EA SPORTS™ UFC® is just a black screen

### Screenshots

![Screenshot_13](https://github.com/user-attachments/assets/58854f5d-25b0-440a-9eee-00219ea594ea)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17603471/shad_log.txt)

**Comment by thecatontheceiling** [comment]
I wonder what goes through your head when reading "(only released versions are acceptable)" and then writing 0.4.1
