### ISSUE TITLE
Hokuto ga Gotoku/Fist of the North Star: Lost Paradise (Asia)

### ISSUE THREAD

**Issue by TheLostNinja** [shadps4-emu/shadps4-game-compatibility#953]
### Game Name

人中北斗

### Game code

CUSA10053

### Game version

1.00

### Used emulator's version (only released versions are acceptable)

0.4.1 WIP

### Current status

Menus

### Operating System

Windows

### Error

Mirroring of each image low half and upper right quarter.

### Description

See the screenshots.

### Screenshots

![2024-11-02_18-13-48](https://github.com/user-attachments/assets/111782c1-54e3-4933-9975-73dc24d56308)
![2024-11-02_18-16-23](https://github.com/user-attachments/assets/1ff5778e-2073-4fc9-954c-8d544ab8a816)
![2024-11-02_18-17-54](https://github.com/user-attachments/assets/b1dc1548-aee9-4b19-a0aa-0d32fb1df446)
![2024-11-02_18-18-37](https://github.com/user-attachments/assets/43e88672-c061-417b-b4bd-b08186736fd4)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/17607233/shad_log.txt)

**Comment by georgemoralis** [comment]
only release versions pls
