### ISSUE TITLE
CUSA04518 - Hatsune Miku: Project Diva X

### ISSUE THREAD

**Issue by Jomanakk** [shadps4-emu/shadps4-game-compatibility#97]
### Game Name

Hatsune Miku: Project Diva X

### Game code

CUSA04518

### Game version

v1.00

### Used emulator's version (only released versions are acceptable)

v0.1.0

### Current status

Nothing

### Error

See log

### Description

Crashes on startup
Nothing renders.

### Screenshots

![image](https://github.com/shadps4-emu/shadps4-game-compatibility/assets/107001229/de1a95d8-3e3e-46f3-a476-32de96d5efc7)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/16098114/shad_log.txt)

**Comment by georgemoralis** [comment]
already reported in #49
