### ISSUE TITLE
games

### ISSUE THREAD

**Issue by winrar1387** [shadps4-emu/shadps4-game-compatibility#990]
### Game Name

Cyberpunk2977

### Game code

CUSA16596

### Game version

v0.3.0

### Used emulator's version (only released versions are acceptable)

v0.3.0

### Current status

Nothing

### Operating System

Windows

### Error

[Core] stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x97fffc064
[Core] stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x97fffc064
[Core.Linker] module.cpp:Start:71: Module started : libSceJobManager
[Core.Linker] module.cpp:Start:71: Module started : libSceNpToolkit2
[Core.Linker] module.cpp:Start:71: Module started : libSceS3DConversion
[Kernel.Vmm] memory_management.cpp:sceKernelGetDirectMemorySize:19: called
[Kernel.Vmm] memory_management.cpp:sceKernelAvailableDirectMemorySize:79: called searchStart = 0x0, searchEnd = 0x12e900000, alignment = 0x0
[Kernel.Vmm] memory_management.cpp:sceKernelGetDirectMemorySize:19: called

This is the last thing it logs before repeating the same error until it closes.

### Description

A black windows opens for a few seconds before it closes/cashes                                                                                                                                           No sys_modules used

### Screenshots

No response

### Log File

shad_log.txt

**Comment by georgemoralis** [comment]
wrong title and duplicate
